import type { ExerciseDef } from "./types";

/**
 * Resistance band work. Bands travel, cost little, and scale by stepping
 * wider or doubling up, which makes them the backbone of a home program.
 */
export const BAND_EXERCISES: ExerciseDef[] = [
  {
    id: "band_pushup",
    name: "Banded Push-up",
    equipment: ["bands"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps"],
    compound: true,
    level: 2,
    unit: "reps",
    loads: ["shoulder", "wrist", "elbow"],
    easier: "pushup",
    substitutes: ["pushup", "band_chest_press"],
    cues: ["Band across your upper back, ends under your hands."],
  },
  {
    id: "band_chest_press",
    name: "Band Chest Press",
    equipment: ["bands"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps", "Front delts"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["shoulder", "elbow"],
    substitutes: ["db_bench", "pushup"],
    cues: ["Anchor the band behind you at chest height.", "Press forward and slightly together."],
  },
  {
    id: "band_overhead_press",
    name: "Band Overhead Press",
    equipment: ["bands"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Triceps"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["shoulder", "elbow"],
    substitutes: ["db_shoulder_press", "pike_pushup"],
    cues: ["Stand on the band, press from shoulder height."],
  },
  {
    id: "band_row",
    name: "Band Row",
    equipment: ["bands"],
    pattern: "horizontal_pull",
    muscles: ["Upper back", "Lats", "Biceps"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["elbow"],
    lowImpact: true,
    substitutes: ["db_row", "cable_row", "inverted_row"],
    cues: ["Anchor at chest height.", "Squeeze the shoulder blades, elbows past your ribs."],
  },
  {
    id: "band_pulldown",
    name: "Band Pulldown",
    equipment: ["bands"],
    pattern: "vertical_pull",
    muscles: ["Lats", "Biceps"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["elbow"],
    lowImpact: true,
    substitutes: ["lat_pulldown", "pullup"],
    cues: ["Anchor above head height and pull down to your chest."],
  },
  {
    id: "band_face_pull",
    name: "Band Face Pull",
    equipment: ["bands"],
    pattern: "isolation",
    muscles: ["Rear delts", "Upper back"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: [],
    lowImpact: true,
    substitutes: ["face_pull", "rear_delt_fly"],
    cues: ["Pull to your forehead, hands finishing wide."],
  },
  {
    id: "band_pull_apart",
    name: "Band Pull-Apart",
    equipment: ["bands"],
    pattern: "isolation",
    muscles: ["Rear delts", "Upper back"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: [],
    lowImpact: true,
    cues: ["Arms straight, pull the band apart across your chest."],
  },
  {
    id: "band_squat",
    name: "Band Squat",
    equipment: ["bands"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["knee", "hip"],
    substitutes: ["goblet_squat", "bw_squat"],
    cues: ["Stand on the band, ends held at your shoulders."],
  },
  {
    id: "band_rdl",
    name: "Band Romanian Deadlift",
    equipment: ["bands"],
    pattern: "hinge",
    muscles: ["Hamstrings", "Glutes"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["hip", "spine"],
    substitutes: ["db_rdl", "single_leg_rdl_bw"],
    cues: ["Stand on the band and hinge at the hips."],
  },
  {
    id: "band_good_morning",
    name: "Band Good Morning",
    equipment: ["bands"],
    pattern: "hinge",
    muscles: ["Hamstrings", "Glutes", "Lower back"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["hip", "spine"],
    substitutes: ["bw_good_morning"],
  },
  {
    id: "band_hip_thrust",
    name: "Band Hip Thrust",
    equipment: ["bands"],
    pattern: "hinge",
    muscles: ["Glutes"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["hip"],
    lowImpact: true,
    substitutes: ["glute_bridge", "hip_thrust"],
  },
  {
    id: "band_lateral_walk",
    name: "Band Lateral Walk",
    equipment: ["bands"],
    pattern: "isolation",
    muscles: ["Glutes"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["hip", "knee"],
    lowImpact: true,
    cues: ["Band above the knees, small controlled side steps."],
  },
  {
    id: "band_lateral_raise",
    name: "Band Lateral Raise",
    equipment: ["bands"],
    pattern: "isolation",
    muscles: ["Side delts"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["shoulder"],
    substitutes: ["lateral_raise"],
  },
  {
    id: "band_curl",
    name: "Band Curl",
    equipment: ["bands"],
    pattern: "isolation",
    muscles: ["Biceps"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["elbow"],
    substitutes: ["db_curl"],
  },
  {
    id: "band_triceps_pushdown",
    name: "Band Triceps Pushdown",
    equipment: ["bands"],
    pattern: "isolation",
    muscles: ["Triceps"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["elbow"],
    substitutes: ["triceps_pushdown"],
  },
  {
    id: "band_pallof_press",
    name: "Pallof Press",
    equipment: ["bands"],
    pattern: "core",
    muscles: ["Core", "Obliques"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["spine"],
    lowImpact: true,
    cues: ["Anchor at chest height to your side.", "Press straight out and resist the twist."],
  },
];
