import type { ExerciseDef } from "./types";

/**
 * Bodyweight movements, arranged as ladders. Every pattern starts at something
 * a deconditioned beginner can do on day one and climbs to an advanced version,
 * linked by `easier` / `harder` so the generator can pick the right rung.
 */
export const BODYWEIGHT_EXERCISES: ExerciseDef[] = [
  // ---- horizontal push ladder ----
  {
    id: "wall_pushup",
    name: "Wall Push-up",
    equipment: ["bodyweight"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps", "Front delts"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["shoulder", "wrist", "elbow"],
    harder: "incline_pushup",
    lowImpact: true,
    cues: ["Stand far enough back that your chest reaches the wall.", "Keep a straight line from head to heels."],
  },
  {
    id: "incline_pushup",
    name: "Incline Push-up",
    equipment: ["bodyweight"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps", "Front delts"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["shoulder", "wrist", "elbow"],
    easier: "wall_pushup",
    harder: "knee_pushup",
    lowImpact: true,
    cues: ["Hands on a bench, step or sturdy table.", "The lower the surface, the harder it gets."],
  },
  {
    id: "knee_pushup",
    name: "Knee Push-up",
    equipment: ["bodyweight"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps", "Front delts"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["shoulder", "wrist", "elbow"],
    floor: true,
    easier: "incline_pushup",
    harder: "pushup",
    cues: ["Keep hips in line with shoulders — don't let them sag.", "Lower until your chest is a fist off the floor."],
  },
  {
    id: "pushup",
    name: "Push-up",
    equipment: ["bodyweight"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps", "Front delts"],
    compound: true,
    level: 2,
    unit: "reps",
    loadable: true,
    loads: ["shoulder", "wrist", "elbow"],
    floor: true,
    easier: "knee_pushup",
    harder: "decline_pushup",
    substitutes: ["db_bench", "machine_chest_press", "band_pushup"],
    cues: ["Squeeze your glutes so your body stays one straight line.", "Elbows about 45 degrees from your ribs, not flared wide."],
  },
  {
    id: "decline_pushup",
    name: "Decline Push-up",
    equipment: ["bodyweight"],
    pattern: "horizontal_push",
    muscles: ["Upper chest", "Front delts", "Triceps"],
    compound: true,
    level: 2,
    unit: "reps",
    loadable: true,
    loads: ["shoulder", "wrist", "elbow"],
    floor: true,
    easier: "pushup",
    harder: "archer_pushup",
    cues: ["Feet on a chair or step.", "Keep your neck neutral rather than craning up."],
  },
  {
    id: "diamond_pushup",
    name: "Diamond Push-up",
    equipment: ["bodyweight"],
    pattern: "horizontal_push",
    muscles: ["Triceps", "Chest"],
    compound: true,
    level: 2,
    unit: "reps",
    loads: ["shoulder", "wrist", "elbow"],
    floor: true,
    easier: "pushup",
    harder: "archer_pushup",
    cues: ["Index fingers and thumbs form a triangle.", "Keep elbows tracking close to your sides."],
  },
  {
    id: "archer_pushup",
    name: "Archer Push-up",
    equipment: ["bodyweight"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps"],
    compound: true,
    level: 3,
    unit: "reps",
    loads: ["shoulder", "wrist", "elbow"],
    floor: true,
    easier: "decline_pushup",
    harder: "one_arm_pushup",
    cues: ["Shift your weight over one arm; the other stays straight.", "Alternate sides each rep."],
  },
  {
    id: "one_arm_pushup",
    name: "One-Arm Push-up",
    equipment: ["bodyweight"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps", "Core"],
    compound: true,
    level: 3,
    unit: "reps",
    loads: ["shoulder", "wrist", "elbow", "spine"],
    floor: true,
    easier: "archer_pushup",
    cues: ["Widen your feet for a stable base.", "Resist the urge to twist — keep hips square."],
  },
  {
    id: "bench_dip",
    name: "Bench Dip",
    equipment: ["chair"],
    pattern: "horizontal_push",
    muscles: ["Triceps", "Chest"],
    compound: true,
    level: 1,
    unit: "reps",
    loadable: true,
    loads: ["shoulder", "elbow", "wrist"],
    harder: "dip",
    cues: ["Keep your back close to the chair.", "Stop if you feel pinching at the front of the shoulder."],
  },
  {
    id: "dip",
    name: "Parallel Bar Dip",
    equipment: ["bodyweight"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps", "Front delts"],
    compound: true,
    level: 3,
    unit: "reps",
    loadable: true,
    loads: ["shoulder", "elbow", "wrist"],
    easier: "bench_dip",
    cues: ["Lean forward slightly to bias the chest.", "Only descend as far as your shoulders stay comfortable."],
  },

  // ---- vertical push ladder ----
  {
    id: "pike_pushup",
    name: "Pike Push-up",
    equipment: ["bodyweight"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Triceps"],
    compound: true,
    level: 2,
    unit: "reps",
    loads: ["shoulder", "wrist", "elbow"],
    floor: true,
    easier: "incline_pushup",
    harder: "elevated_pike_pushup",
    substitutes: ["db_shoulder_press", "band_overhead_press"],
    cues: ["Hips high, body in an upside-down V.", "Lower the crown of your head toward the floor."],
  },
  {
    id: "elevated_pike_pushup",
    name: "Elevated Pike Push-up",
    equipment: ["chair"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Triceps"],
    compound: true,
    level: 3,
    unit: "reps",
    loads: ["shoulder", "wrist", "elbow"],
    floor: true,
    easier: "pike_pushup",
    harder: "handstand_pushup",
    cues: ["Feet on a chair to shift more weight over your shoulders."],
  },
  {
    id: "wall_handstand_hold",
    name: "Wall Handstand Hold",
    equipment: ["bodyweight"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Core"],
    compound: true,
    level: 3,
    unit: "time",
    loads: ["shoulder", "wrist", "neck"],
    floor: true,
    harder: "handstand_pushup",
    cues: ["Walk your feet up the wall.", "Push the floor away and keep ribs tucked."],
  },
  {
    id: "handstand_pushup",
    name: "Handstand Push-up",
    equipment: ["bodyweight"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Triceps"],
    compound: true,
    level: 3,
    unit: "reps",
    loads: ["shoulder", "wrist", "elbow", "neck"],
    floor: true,
    easier: "elevated_pike_pushup",
    cues: ["Against a wall until you're confident.", "Lower under control — don't drop onto your head."],
  },

  // ---- horizontal pull ladder ----
  {
    id: "table_row",
    name: "Table Row",
    equipment: ["bodyweight"],
    pattern: "horizontal_pull",
    muscles: ["Upper back", "Biceps"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["elbow"],
    harder: "inverted_row",
    lowImpact: true,
    cues: ["Lie under a sturdy table and grip the edge.", "Keep heels down and hips up in a straight line."],
  },
  {
    id: "inverted_row",
    name: "Inverted Row",
    equipment: ["pullup_bar"],
    pattern: "horizontal_pull",
    muscles: ["Upper back", "Lats", "Biceps"],
    compound: true,
    level: 2,
    unit: "reps",
    loadable: true,
    loads: ["elbow"],
    easier: "table_row",
    harder: "feet_elevated_row",
    substitutes: ["db_row", "cable_row", "band_row"],
    cues: ["Set the bar around hip height.", "Pull your chest to the bar, squeezing shoulder blades together."],
  },
  {
    id: "feet_elevated_row",
    name: "Feet-Elevated Inverted Row",
    equipment: ["pullup_bar", "chair"],
    pattern: "horizontal_pull",
    muscles: ["Upper back", "Lats", "Biceps"],
    compound: true,
    level: 3,
    unit: "reps",
    loadable: true,
    loads: ["elbow"],
    easier: "inverted_row",
    cues: ["Feet on a chair puts you closer to horizontal, which is harder."],
  },

  // ---- vertical pull ladder ----
  {
    id: "dead_hang",
    name: "Dead Hang",
    equipment: ["pullup_bar"],
    pattern: "vertical_pull",
    muscles: ["Lats", "Forearms"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["elbow", "wrist"],
    harder: "scapular_pullup",
    cues: ["Hang with straight arms and relaxed shoulders.", "Builds the grip and shoulder tolerance a pull-up needs."],
  },
  {
    id: "scapular_pullup",
    name: "Scapular Pull-up",
    equipment: ["pullup_bar"],
    pattern: "vertical_pull",
    muscles: ["Lats", "Upper back"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["elbow"],
    easier: "dead_hang",
    harder: "negative_pullup",
    cues: ["Arms stay straight; only your shoulder blades move.", "Pull your shoulders down away from your ears."],
  },
  {
    id: "negative_pullup",
    name: "Negative Pull-up",
    equipment: ["pullup_bar"],
    pattern: "vertical_pull",
    muscles: ["Lats", "Biceps"],
    compound: true,
    level: 2,
    unit: "reps",
    loads: ["elbow"],
    easier: "scapular_pullup",
    harder: "pullup",
    cues: ["Jump or step to the top position.", "Lower as slowly as you can — aim for five seconds."],
  },
  {
    id: "band_assisted_pullup",
    name: "Band-Assisted Pull-up",
    equipment: ["pullup_bar", "bands"],
    pattern: "vertical_pull",
    muscles: ["Lats", "Biceps"],
    compound: true,
    level: 2,
    unit: "reps",
    loads: ["elbow"],
    easier: "negative_pullup",
    harder: "pullup",
    cues: ["Loop a band over the bar and put a foot or knee in it.", "Thinner band as you get stronger."],
  },
  {
    id: "pullup",
    name: "Pull-up",
    equipment: ["pullup_bar"],
    pattern: "vertical_pull",
    muscles: ["Lats", "Biceps"],
    compound: true,
    level: 2,
    unit: "reps",
    loadable: true,
    loads: ["elbow"],
    easier: "band_assisted_pullup",
    harder: "archer_pullup",
    substitutes: ["lat_pulldown", "chinup", "band_pulldown"],
    cues: ["Start from a dead hang.", "Lead with your chest, finish with your chin clear of the bar."],
  },
  {
    id: "chinup",
    name: "Chin-up",
    equipment: ["pullup_bar"],
    pattern: "vertical_pull",
    muscles: ["Lats", "Biceps"],
    compound: true,
    level: 2,
    unit: "reps",
    loadable: true,
    loads: ["elbow"],
    easier: "band_assisted_pullup",
    harder: "archer_pullup",
    substitutes: ["pullup", "lat_pulldown"],
    cues: ["Palms facing you, which lets the biceps help more."],
  },
  {
    id: "archer_pullup",
    name: "Archer Pull-up",
    equipment: ["pullup_bar"],
    pattern: "vertical_pull",
    muscles: ["Lats", "Biceps"],
    compound: true,
    level: 3,
    unit: "reps",
    loads: ["elbow"],
    easier: "pullup",
    cues: ["Pull toward one hand while the other arm straightens.", "Alternate sides."],
  },

  // ---- squat ladder ----
  {
    id: "sit_to_stand",
    name: "Sit-to-Stand",
    equipment: ["chair"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["knee", "hip"],
    harder: "box_squat_bw",
    lowImpact: true,
    cues: ["Stand up from a chair without using your hands.", "Sit back down under control rather than dropping."],
  },
  {
    id: "box_squat_bw",
    name: "Box Squat",
    equipment: ["chair"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "reps",
    loadable: true,
    loads: ["knee", "hip"],
    easier: "sit_to_stand",
    harder: "bw_squat",
    lowImpact: true,
    cues: ["Touch the seat lightly, then stand.", "Knees track over your toes."],
  },
  {
    id: "bw_squat",
    name: "Bodyweight Squat",
    equipment: ["bodyweight"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "reps",
    loadable: true,
    loads: ["knee", "hip"],
    easier: "box_squat_bw",
    harder: "split_squat_bw",
    substitutes: ["goblet_squat", "leg_press"],
    cues: ["Sit down and back, chest tall.", "Go as deep as you can without your lower back rounding."],
  },
  {
    id: "split_squat_bw",
    name: "Split Squat",
    equipment: ["bodyweight"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 2,
    unit: "reps",
    loadable: true,
    loads: ["knee", "hip"],
    easier: "bw_squat",
    harder: "bulgarian_split_squat_bw",
    cues: ["Feet in a long stance, back heel lifted.", "Drop straight down rather than forward."],
  },
  {
    id: "bulgarian_split_squat_bw",
    name: "Bulgarian Split Squat",
    equipment: ["chair"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 2,
    unit: "reps",
    loadable: true,
    loads: ["knee", "hip"],
    easier: "split_squat_bw",
    harder: "assisted_pistol_squat",
    substitutes: ["split_squat"],
    cues: ["Rear foot on a chair.", "Most of your weight stays through the front heel."],
  },
  {
    id: "assisted_pistol_squat",
    name: "Assisted Pistol Squat",
    equipment: ["chair"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 2,
    unit: "reps",
    loads: ["knee", "hip", "ankle"],
    easier: "bulgarian_split_squat_bw",
    harder: "pistol_squat",
    cues: ["Hold a doorframe or chair for balance.", "Take the weight through your working leg, not your arms."],
  },
  {
    id: "pistol_squat",
    name: "Pistol Squat",
    equipment: ["bodyweight"],
    pattern: "squat",
    muscles: ["Quads", "Glutes", "Core"],
    compound: true,
    level: 3,
    unit: "reps",
    loads: ["knee", "hip", "ankle"],
    easier: "assisted_pistol_squat",
    cues: ["Free leg stays straight out in front.", "Needs ankle mobility — don't force it."],
  },
  {
    id: "wall_sit",
    name: "Wall Sit",
    equipment: ["bodyweight"],
    pattern: "squat",
    muscles: ["Quads"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["knee"],
    lowImpact: true,
    cues: ["Back flat on the wall, thighs parallel to the floor."],
  },

  // ---- hinge ----
  {
    id: "glute_bridge",
    name: "Glute Bridge",
    equipment: ["mat"],
    pattern: "hinge",
    muscles: ["Glutes", "Hamstrings"],
    compound: true,
    level: 1,
    unit: "reps",
    loadable: true,
    loads: ["hip"],
    harder: "single_leg_glute_bridge",
    lowImpact: true,
    cues: ["Drive through your heels.", "Squeeze the glutes at the top rather than arching your back."],
  },
  {
    id: "single_leg_glute_bridge",
    name: "Single-Leg Glute Bridge",
    equipment: ["mat"],
    pattern: "hinge",
    muscles: ["Glutes", "Hamstrings"],
    compound: true,
    level: 2,
    unit: "reps",
    loadable: true,
    loads: ["hip"],
    easier: "glute_bridge",
    harder: "nordic_negative",
    lowImpact: true,
    cues: ["One foot planted, the other knee pulled in.", "Keep hips level throughout."],
  },
  {
    id: "bw_good_morning",
    name: "Bodyweight Good Morning",
    equipment: ["bodyweight"],
    pattern: "hinge",
    muscles: ["Hamstrings", "Glutes", "Lower back"],
    compound: true,
    level: 1,
    unit: "reps",
    loadable: true,
    loads: ["spine", "hip"],
    harder: "single_leg_rdl_bw",
    cues: ["Hands behind your head, soft knees.", "Push hips back and feel a stretch behind the thighs."],
  },
  {
    id: "single_leg_rdl_bw",
    name: "Single-Leg Romanian Deadlift",
    equipment: ["bodyweight"],
    pattern: "hinge",
    muscles: ["Hamstrings", "Glutes"],
    compound: true,
    level: 2,
    unit: "reps",
    loadable: true,
    loads: ["hip", "spine"],
    easier: "bw_good_morning",
    substitutes: ["db_rdl", "rdl"],
    cues: ["Hinge at the hip, back leg rising behind you.", "Keep hips square to the floor."],
  },
  {
    id: "nordic_negative",
    name: "Nordic Curl Negative",
    equipment: ["mat"],
    pattern: "hinge",
    muscles: ["Hamstrings"],
    compound: true,
    level: 3,
    unit: "reps",
    loads: ["knee", "hip"],
    easier: "single_leg_glute_bridge",
    cues: ["Anchor your heels, lower as slowly as possible.", "Catch yourself with your hands."],
  },

  // ---- lunge ----
  {
    id: "reverse_lunge_bw",
    name: "Reverse Lunge",
    equipment: ["bodyweight"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "reps",
    loadable: true,
    loads: ["knee", "hip"],
    harder: "walking_lunge_bw",
    cues: ["Step backwards rather than forwards — kinder on the knees.", "Front shin stays roughly vertical."],
  },
  {
    id: "walking_lunge_bw",
    name: "Walking Lunge",
    equipment: ["bodyweight"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 2,
    unit: "reps",
    loadable: true,
    loads: ["knee", "hip"],
    easier: "reverse_lunge_bw",
    harder: "jumping_lunge",
    substitutes: ["walking_lunge"],
    cues: ["Long strides, torso upright."],
  },
  {
    id: "step_up_bw",
    name: "Step-up",
    equipment: ["chair"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "reps",
    loadable: true,
    loads: ["knee", "hip"],
    lowImpact: true,
    cues: ["Drive through the heel of the stepping foot.", "Lower under control rather than dropping back."],
  },

  // ---- plyometric ----
  {
    id: "jump_squat",
    name: "Jump Squat",
    equipment: ["bodyweight"],
    pattern: "plyometric",
    muscles: ["Quads", "Glutes", "Calves"],
    compound: true,
    level: 2,
    unit: "reps",
    loads: ["knee", "hip", "ankle"],
    harder: "jumping_lunge",
    cues: ["Land softly, absorbing through the hips and knees.", "Quality over quantity — stop when landings get heavy."],
  },
  {
    id: "jumping_lunge",
    name: "Jumping Lunge",
    equipment: ["bodyweight"],
    pattern: "plyometric",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 3,
    unit: "reps",
    loads: ["knee", "hip", "ankle"],
    easier: "jump_squat",
    cues: ["Switch legs mid-air.", "Land soft and controlled."],
  },
  {
    id: "box_jump",
    name: "Box Jump",
    equipment: ["chair"],
    pattern: "plyometric",
    muscles: ["Quads", "Glutes", "Calves"],
    compound: true,
    level: 2,
    unit: "reps",
    loads: ["knee", "hip", "ankle"],
    cues: ["Use a stable surface at a height you can clear easily.", "Step back down rather than jumping down."],
  },
  {
    id: "burpee",
    name: "Burpee",
    equipment: ["bodyweight"],
    pattern: "plyometric",
    muscles: ["Full body"],
    compound: true,
    level: 2,
    unit: "reps",
    loads: ["shoulder", "wrist", "knee", "spine"],
    floor: true,
    cues: ["Drop to a plank, hop feet back in, stand and reach.", "Drop the jump if it's aggravating anything."],
  },

  // ---- core ----
  {
    id: "dead_bug",
    name: "Dead Bug",
    equipment: ["mat"],
    pattern: "core",
    muscles: ["Core"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: [],
    harder: "plank",
    lowImpact: true,
    cues: ["Lower opposite arm and leg while keeping your lower back flat.", "Move slowly and keep breathing."],
  },
  {
    id: "plank",
    name: "Plank",
    equipment: ["mat"],
    pattern: "core",
    muscles: ["Core"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["spine"],
    easier: "dead_bug",
    harder: "side_plank",
    lowImpact: true,
    cues: ["Squeeze glutes and brace your stomach.", "Hips level — no sagging or piking."],
  },
  {
    id: "side_plank",
    name: "Side Plank",
    equipment: ["mat"],
    pattern: "core",
    muscles: ["Obliques", "Core"],
    compound: false,
    level: 2,
    unit: "time",
    loads: ["spine"],
    easier: "plank",
    harder: "hollow_hold",
    cues: ["Stack your feet and lift your hips high.", "Drop to a knee if the full version is too much."],
  },
  {
    id: "hollow_hold",
    name: "Hollow Hold",
    equipment: ["mat"],
    pattern: "core",
    muscles: ["Core"],
    compound: false,
    level: 2,
    unit: "time",
    loads: ["spine"],
    easier: "side_plank",
    harder: "hanging_leg_raise",
    cues: ["Press your lower back into the floor.", "Lower arms and legs only as far as you can keep it pressed."],
  },
  {
    id: "mountain_climber",
    name: "Mountain Climber",
    equipment: ["bodyweight"],
    pattern: "core",
    muscles: ["Core", "Hip flexors"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["wrist"],
    floor: true,
    cues: ["Drive knees toward your chest without your hips bouncing."],
  },
  {
    id: "bicycle_crunch",
    name: "Bicycle Crunch",
    equipment: ["mat"],
    pattern: "core",
    muscles: ["Core", "Obliques"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["neck", "spine"],
    lowImpact: true,
    cues: ["Rotate through the ribs, not by yanking on your neck."],
  },
  {
    id: "hanging_knee_raise",
    name: "Hanging Knee Raise",
    equipment: ["pullup_bar"],
    pattern: "core",
    muscles: ["Core", "Hip flexors"],
    compound: false,
    level: 2,
    unit: "reps",
    loadable: true,
    loads: ["spine"],
    harder: "hanging_leg_raise",
    cues: ["Curl your knees up rather than just swinging them."],
  },
  {
    id: "hanging_leg_raise",
    name: "Hanging Leg Raise",
    equipment: ["pullup_bar"],
    pattern: "core",
    muscles: ["Core", "Hip flexors"],
    compound: false,
    level: 3,
    unit: "reps",
    loadable: true,
    loads: ["spine"],
    easier: "hanging_knee_raise",
    cues: ["Straight legs, controlled on the way down."],
  },
  {
    id: "ab_wheel",
    name: "Ab Wheel Rollout",
    equipment: ["bodyweight"],
    pattern: "core",
    muscles: ["Core"],
    compound: false,
    level: 3,
    unit: "reps",
    loads: ["spine", "shoulder"],
    floor: true,
    cues: ["Roll out only as far as you can keep your back flat."],
  },
  {
    id: "bird_dog",
    name: "Bird Dog",
    equipment: ["mat"],
    pattern: "core",
    muscles: ["Core", "Lower back", "Glutes"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: [],
    lowImpact: true,
    cues: ["Extend opposite arm and leg, keeping hips square.", "Pause a second at full extension."],
  },
  {
    id: "back_extension_bw",
    name: "Back Extension",
    equipment: ["mat"],
    pattern: "core",
    muscles: ["Lower back", "Glutes"],
    compound: false,
    level: 1,
    unit: "reps",
    loadable: true,
    loads: ["spine"],
    lowImpact: true,
    cues: ["Lift your chest a few inches; this is a small movement."],
  },

  // ---- isolation ----
  {
    id: "calf_raise",
    name: "Calf Raise",
    equipment: ["bodyweight"],
    pattern: "isolation",
    muscles: ["Calves"],
    compound: false,
    level: 1,
    unit: "reps",
    loadable: true,
    loads: ["ankle"],
    harder: "single_leg_calf_raise",
    lowImpact: true,
    cues: ["Full range — heels all the way down, up onto the toes."],
  },
  {
    id: "single_leg_calf_raise",
    name: "Single-Leg Calf Raise",
    equipment: ["bodyweight"],
    pattern: "isolation",
    muscles: ["Calves"],
    compound: false,
    level: 2,
    unit: "reps",
    loadable: true,
    loads: ["ankle"],
    easier: "calf_raise",
    cues: ["Steady yourself against a wall."],
  },
  {
    id: "superman_hold",
    name: "Superman Hold",
    equipment: ["mat"],
    pattern: "isolation",
    muscles: ["Lower back", "Glutes"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["spine"],
    lowImpact: true,
    cues: ["Lift arms and legs a small way off the floor and hold."],
  },

  // ---- added ----
  {
    id: "lateral_lunge_bw",
    name: "Side Lunge",
    equipment: ["bodyweight"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes", "Adductors"],
    compound: true,
    level: 1,
    unit: "reps",
    loadable: true,
    loads: ["knee", "hip"],
    substitutes: ["reverse_lunge_bw", "split_squat_bw"],
    cues: ["Take a wide step to the side and sit back into that hip, other leg straight.", "Keep both feet flat and push back to the middle."],
  },
  {
    id: "side_lying_leg_raise",
    name: "Side-Lying Leg Raise",
    equipment: ["mat"],
    pattern: "isolation",
    muscles: ["Glutes"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["hip"],
    lowImpact: true,
    substitutes: ["standing_hip_abduction", "band_lateral_walk"],
    cues: ["Lie on your side, bottom knee bent for support.", "Lift the top leg with the toes pointing forward, not up at the ceiling."],
  },
  {
    id: "kneeling_side_plank",
    name: "Kneeling Side Plank",
    equipment: ["mat"],
    pattern: "core",
    muscles: ["Obliques", "Core"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["spine", "shoulder"],
    lowImpact: true,
    harder: "side_plank",
    substitutes: ["side_plank", "band_pallof_press"],
    cues: ["On your side, propped on the forearm, knees bent behind you.", "Lift your hips so there's a straight line from knees to head."],
  },
];
