import type { ExerciseDef } from "./types";

/**
 * Structured cardio. Split by intent rather than listing machines, because
 * "30 minutes steady" and "8 rounds of 30 seconds hard" are different sessions
 * even on the same bike. This is what the endurance and fat-loss goals need.
 */
export const CONDITIONING_EXERCISES: ExerciseDef[] = [
  // ---- steady state ----
  {
    id: "steady_walk",
    name: "Brisk Walk",
    equipment: ["bodyweight"],
    pattern: "conditioning",
    muscles: ["Legs", "Heart"],
    compound: true,
    level: 1,
    unit: "time",
    loads: ["ankle", "knee"],
    lowImpact: true,
    harder: "incline_walk",
    cues: ["A pace where you can talk but not sing."],
  },
  {
    id: "incline_walk",
    name: "Incline Walk",
    equipment: ["cardio"],
    pattern: "conditioning",
    muscles: ["Legs", "Heart"],
    compound: true,
    level: 1,
    unit: "time",
    loads: ["ankle", "knee"],
    lowImpact: true,
    easier: "steady_walk",
    harder: "steady_run",
    substitutes: ["steady_bike"],
    cues: ["Raise the incline rather than the speed to keep it low-impact."],
  },
  {
    id: "steady_run",
    name: "Steady Run",
    equipment: ["bodyweight"],
    pattern: "conditioning",
    muscles: ["Legs", "Heart"],
    compound: true,
    level: 2,
    unit: "distance",
    loads: ["knee", "ankle", "hip"],
    easier: "incline_walk",
    harder: "tempo_run",
    substitutes: ["steady_bike", "steady_row"],
    cues: ["Conversational pace. Most running should feel easier than you think."],
  },
  {
    id: "steady_bike",
    name: "Steady Bike",
    equipment: ["cardio"],
    pattern: "conditioning",
    muscles: ["Legs", "Heart"],
    compound: true,
    level: 1,
    unit: "time",
    loads: ["knee"],
    lowImpact: true,
    substitutes: ["steady_row", "incline_walk"],
    cues: ["A pace you could hold a conversation at.", "Seat high enough that your knee is only slightly bent at the bottom."],
  },
  {
    id: "steady_row",
    name: "Steady Row",
    equipment: ["cardio"],
    pattern: "conditioning",
    muscles: ["Full body", "Heart"],
    compound: true,
    level: 1,
    unit: "distance",
    loads: ["spine", "knee", "shoulder"],
    lowImpact: true,
    substitutes: ["steady_bike"],
    cues: ["Legs, then back, then arms. Reverse that on the way in."],
  },
  {
    id: "elliptical",
    name: "Elliptical",
    equipment: ["cardio"],
    pattern: "conditioning",
    muscles: ["Full body", "Heart"],
    compound: true,
    level: 1,
    unit: "time",
    loads: [],
    lowImpact: true,
    substitutes: ["steady_bike"],
    cues: ["Stand tall and push and pull through the handles too.", "A pace you could talk at, but not sing."],
  },
  {
    id: "swim",
    name: "Swim",
    equipment: ["bodyweight"],
    pattern: "conditioning",
    muscles: ["Full body", "Heart"],
    compound: true,
    level: 1,
    unit: "time",
    loads: ["shoulder"],
    lowImpact: true,
    cues: ["Close to zero joint load, which makes it a good fallback when something hurts."],
  },

  // ---- tempo / threshold ----
  {
    id: "tempo_run",
    name: "Tempo Run",
    equipment: ["bodyweight"],
    pattern: "conditioning",
    muscles: ["Legs", "Heart"],
    compound: true,
    level: 3,
    unit: "time",
    loads: ["knee", "ankle", "hip"],
    easier: "steady_run",
    cues: ["Comfortably hard — you could manage short sentences, not a chat.", "Hold it for 20 to 40 minutes."],
  },
  {
    id: "tempo_bike",
    name: "Tempo Bike",
    equipment: ["cardio"],
    pattern: "conditioning",
    muscles: ["Legs", "Heart"],
    compound: true,
    level: 2,
    unit: "time",
    loads: ["knee"],
    lowImpact: true,
    substitutes: ["tempo_run"],
    cues: ["Comfortably hard: you can speak in short sentences, not paragraphs.", "Settle into a pace you can hold for the whole block."],
  },

  // ---- intervals ----
  {
    id: "interval_bike",
    name: "Bike Intervals",
    equipment: ["cardio"],
    pattern: "conditioning",
    muscles: ["Legs", "Heart"],
    compound: true,
    level: 2,
    unit: "time",
    loads: ["knee"],
    lowImpact: true,
    substitutes: ["interval_row", "interval_run"],
    cues: ["Hard efforts with easy spinning between.", "Start with 30 seconds on, 90 seconds off."],
  },
  {
    id: "interval_row",
    name: "Rowing Intervals",
    equipment: ["cardio"],
    pattern: "conditioning",
    muscles: ["Full body", "Heart"],
    compound: true,
    level: 2,
    unit: "time",
    loads: ["spine", "knee", "shoulder"],
    substitutes: ["interval_bike"],
    cues: ["Hard efforts with easy rowing in between.", "Legs, then body, then arms on the way back; reverse on the way in."],
  },
  {
    id: "interval_run",
    name: "Running Intervals",
    equipment: ["bodyweight"],
    pattern: "conditioning",
    muscles: ["Legs", "Heart"],
    compound: true,
    level: 3,
    unit: "time",
    loads: ["knee", "ankle", "hip"],
    substitutes: ["interval_bike"],
    cues: ["Warm up properly first — intervals on cold legs is how people get hurt."],
  },
  {
    id: "hill_sprint",
    name: "Hill Sprint",
    equipment: ["bodyweight"],
    pattern: "conditioning",
    muscles: ["Legs", "Heart"],
    compound: true,
    level: 3,
    unit: "reps",
    loads: ["knee", "ankle", "hip"],
    cues: ["The hill limits your speed, which makes it kinder than flat sprinting.", "Walk back down as recovery."],
  },
  {
    id: "jump_rope",
    name: "Jump Rope",
    equipment: ["bodyweight"],
    pattern: "conditioning",
    muscles: ["Calves", "Heart"],
    compound: true,
    level: 2,
    unit: "time",
    loads: ["ankle", "knee"],
    cues: ["Small bounces, wrists doing the work."],
  },
  {
    id: "kb_swing_conditioning",
    name: "Kettlebell Swing Intervals",
    equipment: ["kettlebell"],
    pattern: "conditioning",
    muscles: ["Full body", "Heart"],
    compound: true,
    level: 2,
    unit: "time",
    loads: ["spine", "hip", "shoulder"],
    substitutes: ["interval_bike"],
    cues: ["Sets of 15 to 20 with short rests hit the heart hard without impact."],
  },
  {
    id: "stair_climb",
    name: "Stair Climb",
    equipment: ["bodyweight"],
    pattern: "conditioning",
    muscles: ["Legs", "Heart"],
    compound: true,
    level: 1,
    unit: "time",
    loads: ["knee", "hip"],
    substitutes: ["incline_walk"],
    cues: ["Steady pace, a hand on the rail.", "Take them one at a time; walking down is part of it."],
  },

  // ---- added: cardio that doesn't need a machine or a pavement ----
  {
    id: "marching_in_place",
    name: "Marching on the Spot",
    equipment: ["bodyweight"],
    pattern: "conditioning",
    muscles: ["Legs", "Hip flexors"],
    compound: true,
    level: 1,
    unit: "time",
    loads: [],
    lowImpact: true,
    substitutes: ["steady_walk", "seated_march"],
    cues: ["Lift the knees and swing the arms, fast enough to breathe harder but still talk.", "Near a counter or chair if you want something to hold."],
  },
  {
    id: "walk_intervals",
    name: "Brisk Walk Intervals",
    equipment: ["bodyweight"],
    pattern: "conditioning",
    muscles: ["Legs"],
    compound: true,
    level: 2,
    unit: "time",
    loads: ["ankle", "knee"],
    lowImpact: true,
    substitutes: ["steady_walk", "interval_bike"],
    cues: ["Alternate a minute walking as fast as you can with a minute at an easy pace.", "Fast enough that talking is hard, never so fast you break into a run."],
  },
  {
    id: "shadow_boxing",
    name: "Shadow Boxing",
    equipment: ["bodyweight"],
    pattern: "conditioning",
    muscles: ["Shoulders", "Core"],
    compound: true,
    level: 2,
    unit: "time",
    loads: ["shoulder"],
    lowImpact: true,
    cues: ["Light on your feet, punches crisp but never fully locking the elbow.", "Work in rounds: thirty seconds hard, thirty easy."],
  },
];
