import type { ExerciseDef } from "./types";

/**
 * Seated and supported work for people who are older, deconditioned, carrying
 * an injury, or simply starting from a low base. Everything here can be done
 * from a chair or with support, and none of it requires getting to the floor.
 */
export const LOW_IMPACT_EXERCISES: ExerciseDef[] = [
  {
    id: "seated_march",
    name: "Seated March",
    equipment: ["chair"],
    pattern: "conditioning",
    muscles: ["Hip flexors", "Core"],
    compound: true,
    level: 1,
    unit: "time",
    loads: [],
    lowImpact: true,
    cues: ["Sit tall and lift one knee at a time, as if marching."],
  },
  {
    id: "seated_press",
    name: "Seated Overhead Press",
    equipment: ["chair", "dumbbell"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Triceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder", "elbow"],
    lowImpact: true,
    substitutes: ["db_shoulder_press"],
    cues: ["Back supported by the chair.", "Press only as high as stays comfortable."],
  },
  {
    id: "seated_row_band",
    name: "Seated Band Row",
    equipment: ["chair", "bands"],
    pattern: "horizontal_pull",
    muscles: ["Upper back", "Biceps"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["shoulder", "elbow"],
    lowImpact: true,
    substitutes: ["band_row", "cable_row"],
    cues: ["Band round your feet, pull the handles to your ribs."],
  },
  {
    id: "seated_curl",
    name: "Seated Curl",
    equipment: ["chair", "dumbbell"],
    pattern: "isolation",
    muscles: ["Biceps"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    lowImpact: true,
    substitutes: ["db_curl"],
  },
  {
    id: "seated_leg_extension",
    name: "Seated Leg Extension",
    equipment: ["chair"],
    pattern: "isolation",
    muscles: ["Quads"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["knee"],
    lowImpact: true,
    substitutes: ["leg_extension"],
    cues: ["Straighten one leg out in front, hold a moment, lower slowly."],
  },
  {
    id: "seated_calf_raise",
    name: "Seated Calf Raise",
    equipment: ["chair"],
    pattern: "isolation",
    muscles: ["Calves"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["ankle"],
    lowImpact: true,
    substitutes: ["calf_raise"],
  },
  {
    id: "supported_squat",
    name: "Supported Squat",
    equipment: ["chair"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["knee", "hip"],
    lowImpact: true,
    harder: "sit_to_stand",
    substitutes: ["bw_squat"],
    cues: ["Hold the chair back for balance.", "Take as much weight through your legs as you comfortably can."],
  },
  {
    id: "wall_pushup_low",
    name: "Counter Push-up",
    equipment: ["bodyweight"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["shoulder", "wrist"],
    lowImpact: true,
    substitutes: ["wall_pushup", "incline_pushup"],
    cues: ["Hands on a kitchen counter — steadier than a wall, easier than the floor."],
  },
  {
    id: "standing_hip_abduction",
    name: "Standing Hip Abduction",
    equipment: ["chair"],
    pattern: "isolation",
    muscles: ["Glutes"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["hip"],
    lowImpact: true,
    cues: ["Hold the chair, lift one leg out to the side.", "Keep your torso upright rather than leaning away."],
  },
  {
    id: "standing_hamstring_curl",
    name: "Standing Hamstring Curl",
    equipment: ["chair"],
    pattern: "isolation",
    muscles: ["Hamstrings"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["knee"],
    lowImpact: true,
  },
  {
    id: "heel_toe_raise",
    name: "Heel and Toe Raise",
    equipment: ["chair"],
    pattern: "isolation",
    muscles: ["Calves", "Shins"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["ankle"],
    lowImpact: true,
    cues: ["Rock up onto the toes, then back onto the heels. Good for balance."],
  },
  {
    id: "sit_to_stand_assisted",
    name: "Assisted Sit-to-Stand",
    equipment: ["chair"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["knee", "hip"],
    lowImpact: true,
    harder: "sit_to_stand",
    cues: ["Push through the armrests as much as you need to."],
  },
  {
    id: "seated_torso_twist",
    name: "Seated Torso Twist",
    equipment: ["chair"],
    pattern: "core",
    muscles: ["Obliques", "Core"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["spine"],
    lowImpact: true,
    cues: ["Rotate gently from the ribs, not by wrenching the lower back."],
  },
  {
    id: "standing_balance",
    name: "Single-Leg Balance",
    equipment: ["chair"],
    pattern: "core",
    muscles: ["Core", "Ankles"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["ankle"],
    lowImpact: true,
    cues: ["Fingertips on the chair for safety.", "Balance work matters more with age, not less."],
  },
  {
    id: "wall_angel",
    name: "Wall Angel",
    equipment: ["bodyweight"],
    pattern: "mobility",
    muscles: ["Upper back", "Shoulders"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["shoulder"],
    lowImpact: true,
    cues: ["Back against the wall, slide the arms up and down.", "Keep hands and elbows in contact if you can."],
  },
  {
    id: "seated_shoulder_roll",
    name: "Seated Shoulder Roll",
    equipment: ["chair"],
    pattern: "mobility",
    muscles: ["Shoulders", "Upper back"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: [],
    lowImpact: true,
  },
];
