import type { ExerciseDef } from "./types";

/**
 * Seated and supported work for people who are older, deconditioned, carrying
 * an injury, or simply starting from a low base. Everything here can be done
 * from a chair or with support, and none of it requires getting to the floor.
 */
export const LOW_IMPACT_EXERCISES: ExerciseDef[] = [
  {
    id: "seated_march",
    name: "Seated March",
    equipment: ["chair"],
    pattern: "conditioning",
    muscles: ["Hip flexors", "Core"],
    compound: true,
    level: 1,
    unit: "time",
    loads: [],
    lowImpact: true,
    cues: ["Sit tall and lift one knee at a time, as if marching."],
  },
  {
    id: "seated_press",
    name: "Seated Overhead Press",
    equipment: ["chair", "dumbbell"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Triceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder", "elbow"],
    lowImpact: true,
    substitutes: ["db_shoulder_press"],
    cues: ["Back supported by the chair.", "Press only as high as stays comfortable."],
  },
  {
    id: "seated_row_band",
    name: "Seated Band Row",
    equipment: ["chair", "bands"],
    pattern: "horizontal_pull",
    muscles: ["Upper back", "Biceps"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["elbow"],
    lowImpact: true,
    substitutes: ["band_row", "cable_row"],
    cues: ["Band round your feet, pull the handles to your ribs."],
  },
  {
    id: "seated_curl",
    name: "Seated Curl",
    equipment: ["chair", "dumbbell"],
    pattern: "isolation",
    muscles: ["Biceps"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    lowImpact: true,
    substitutes: ["db_curl"],
    cues: ["Sit tall with your back against the chair and elbows by your sides.", "Lower slowly — the way down counts as much as the way up."],
  },
  {
    id: "seated_leg_extension",
    name: "Seated Leg Extension",
    equipment: ["chair"],
    pattern: "isolation",
    muscles: ["Quads"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["knee"],
    lowImpact: true,
    substitutes: ["leg_extension"],
    cues: ["Straighten one leg out in front, hold a moment, lower slowly."],
  },
  {
    id: "seated_calf_raise",
    name: "Seated Calf Raise",
    equipment: ["chair"],
    pattern: "isolation",
    muscles: ["Calves"],
    compound: false,
    level: 1,
    unit: "reps",
    loadable: true,
    loads: ["ankle"],
    lowImpact: true,
    substitutes: ["calf_raise"],
    cues: ["Feet flat, lift your heels as high as they go, pause, lower slowly.", "A dumbbell resting on each knee makes it harder."],
  },
  {
    id: "supported_squat",
    name: "Supported Squat",
    equipment: ["chair"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["knee", "hip"],
    lowImpact: true,
    harder: "sit_to_stand",
    substitutes: ["bw_squat"],
    cues: ["Hold the chair back for balance.", "Take as much weight through your legs as you comfortably can."],
  },
  {
    id: "wall_pushup_low",
    name: "Counter Push-up",
    equipment: ["bodyweight"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["shoulder", "wrist"],
    lowImpact: true,
    substitutes: ["wall_pushup", "incline_pushup"],
    cues: ["Hands on a kitchen counter — steadier than a wall, easier than the floor."],
  },
  {
    id: "standing_hip_abduction",
    name: "Standing Hip Abduction",
    equipment: ["chair"],
    pattern: "isolation",
    muscles: ["Glutes"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["hip"],
    lowImpact: true,
    cues: ["Hold the chair, lift one leg out to the side.", "Keep your torso upright rather than leaning away."],
  },
  {
    id: "standing_hamstring_curl",
    name: "Standing Hamstring Curl",
    equipment: ["chair"],
    pattern: "isolation",
    muscles: ["Hamstrings"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["knee"],
    lowImpact: true,
    substitutes: ["leg_curl"],
    cues: ["Hold the chair back and bend one knee to bring the heel toward your bottom.", "Keep your knees side by side; the thigh stays still."],
  },
  {
    id: "heel_toe_raise",
    name: "Heel and Toe Raise",
    equipment: ["chair"],
    pattern: "isolation",
    muscles: ["Calves", "Shins"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["ankle"],
    lowImpact: true,
    cues: ["Rock up onto the toes, then back onto the heels. Good for balance."],
  },
  {
    id: "sit_to_stand_assisted",
    name: "Assisted Sit-to-Stand",
    equipment: ["chair"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["knee", "hip"],
    lowImpact: true,
    harder: "sit_to_stand",
    cues: ["Push through the armrests as much as you need to."],
  },
  {
    id: "seated_torso_twist",
    name: "Seated Torso Twist",
    equipment: ["chair"],
    pattern: "core",
    muscles: ["Obliques", "Core"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["spine"],
    lowImpact: true,
    cues: ["Rotate gently from the ribs, not by wrenching the lower back."],
  },
  /*
   * Balance. Two kinds, alternated through the week: standing still on a
   * narrowing base, and walking on one. The ladder and the walking drills
   * follow the Otago programme, the home exercise plan most falls-prevention
   * trials are built on: heel-to-toe stand, one-leg stand, heel-to-toe walk,
   * sideways and backwards walking, toe and heel walking, walking and turning.
   * Everything is done beside a kitchen counter, hands hovering over it.
   */
  {
    // The balance exercise for someone who owns nothing: a kitchen counter
    // does the chair's job.
    id: "tandem_stance",
    name: "Heel-to-Toe Stand",
    equipment: ["bodyweight"],
    pattern: "balance",
    muscles: ["Core", "Ankles"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["ankle"],
    lowImpact: true,
    harder: "standing_balance",
    cues: [
      "Stand one foot directly in front of the other, heel touching toe, next to a counter or wall.",
      "Hands hover just above the counter, ready if you need it. Swap which foot is in front each set.",
    ],
    substitutes: ["standing_balance"],
  },
  {
    id: "standing_balance",
    name: "Single-Leg Balance",
    equipment: ["chair"],
    pattern: "balance",
    muscles: ["Core", "Ankles"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["ankle"],
    lowImpact: true,
    easier: "tandem_stance",
    harder: "single_leg_head_turns",
    cues: [
      "Stand beside the back of a chair, fingertips resting on it for safety.",
      "Lift one foot a few centimetres and hold. Both legs count as one set.",
      "As it gets easier, lighten your touch until your hand just hovers.",
    ],
    substitutes: ["tandem_stance"],
  },
  {
    id: "single_leg_head_turns",
    name: "Single-Leg Balance with Head Turns",
    equipment: ["chair"],
    pattern: "balance",
    muscles: ["Core", "Ankles"],
    compound: false,
    level: 2,
    unit: "time",
    loads: ["ankle", "neck"],
    lowImpact: true,
    easier: "standing_balance",
    cues: [
      "Balance on one leg beside the chair, then turn your head slowly left and right.",
      "Your eyes help you balance, so moving them makes it harder. Stop if you feel dizzy.",
    ],
    substitutes: ["standing_balance"],
  },
  {
    id: "tandem_walk",
    name: "Heel-to-Toe Walk",
    equipment: ["bodyweight"],
    pattern: "balance",
    muscles: ["Core", "Ankles"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["ankle"],
    lowImpact: true,
    harder: "backwards_tandem_walk",
    substitutes: ["sideways_walk", "tandem_stance"],
    cues: [
      "Walk along the kitchen counter, placing each heel right in front of the other toes.",
      "Each step counts as one rep. Look ahead, not down at your feet.",
    ],
  },
  {
    id: "backwards_tandem_walk",
    name: "Backwards Heel-to-Toe Walk",
    equipment: ["bodyweight"],
    pattern: "balance",
    muscles: ["Core", "Ankles"],
    compound: false,
    level: 2,
    unit: "reps",
    loads: ["ankle"],
    lowImpact: true,
    easier: "tandem_walk",
    substitutes: ["backwards_walk"],
    cues: [
      "Along the counter again, but backwards: each toe goes right behind the other heel.",
      "Slow and deliberate. Each step is one rep.",
    ],
  },
  {
    id: "sideways_walk",
    name: "Sideways Walk",
    equipment: ["bodyweight"],
    pattern: "balance",
    muscles: ["Glutes", "Ankles"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["hip", "ankle"],
    lowImpact: true,
    substitutes: ["tandem_walk", "backwards_walk"],
    cues: [
      "Facing the counter, step sideways along it, feet apart then together.",
      "Stand tall with your knees soft. Each step is one rep; go both ways.",
    ],
  },
  {
    id: "backwards_walk",
    name: "Backwards Walk",
    equipment: ["bodyweight"],
    pattern: "balance",
    muscles: ["Core", "Ankles"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["ankle"],
    lowImpact: true,
    harder: "backwards_tandem_walk",
    substitutes: ["sideways_walk", "tandem_walk"],
    cues: [
      "Walk backwards along the counter, a hand hovering over it.",
      "Reach back with your toes first. Each step is one rep; check the floor behind is clear.",
    ],
  },
  {
    id: "toe_heel_walk",
    name: "Toe and Heel Walk",
    equipment: ["bodyweight"],
    pattern: "balance",
    muscles: ["Calves", "Shins"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["ankle"],
    lowImpact: true,
    substitutes: ["tandem_walk", "heel_toe_raise"],
    cues: [
      "Walk along the counter up on your toes, then walk back on your heels.",
      "Each step is one rep. Strong ankles are what catch a stumble.",
    ],
  },
  {
    id: "walk_and_turn",
    name: "Walk and Turn",
    equipment: ["bodyweight"],
    pattern: "balance",
    muscles: ["Core", "Ankles"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["ankle", "hip"],
    lowImpact: true,
    substitutes: ["sideways_walk", "backwards_walk"],
    cues: [
      "Walk a few steps at normal pace, turn around in a small circle, and walk back.",
      "Each turn is one rep. Alternate turning left and right.",
    ],
  },

  {
    id: "wall_angel",
    name: "Wall Angel",
    equipment: ["bodyweight"],
    pattern: "mobility",
    muscles: ["Upper back", "Shoulders"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["shoulder"],
    lowImpact: true,
    cues: ["Back against the wall, slide the arms up and down.", "Keep hands and elbows in contact if you can."],
  },
  {
    id: "seated_shoulder_roll",
    name: "Seated Shoulder Roll",
    equipment: ["chair"],
    pattern: "mobility",
    muscles: ["Shoulders", "Upper back"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: [],
    lowImpact: true,
    cues: ["Lift the shoulders up to your ears, roll them back and down.", "Slow circles; reverse halfway."],
  },

  /*
   * Standing and seated versions of work that's usually done on the floor or
   * on a high step, for anyone who shouldn't have to get down to the mat or
   * climb onto a chair to train.
   */
  {
    id: "incline_plank",
    name: "Counter Plank",
    equipment: ["bodyweight"],
    pattern: "core",
    muscles: ["Core"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["shoulder", "wrist"],
    lowImpact: true,
    harder: "plank",
    substitutes: ["plank", "dead_bug"],
    cues: [
      "Hands on a kitchen counter, walk your feet back until your body is one straight line.",
      "Brace as if about to be nudged. The lower the surface, the harder it is.",
    ],
  },
  {
    id: "seated_lean_back",
    name: "Seated Lean-Back",
    equipment: ["chair"],
    pattern: "core",
    muscles: ["Core"],
    compound: false,
    level: 1,
    unit: "time",
    loads: [],
    lowImpact: true,
    substitutes: ["incline_plank", "dead_bug"],
    cues: [
      "Sit near the front of the chair, arms crossed, back straight.",
      "Lean back a few centimetres from the hips — not by rounding — and hold.",
    ],
  },
  {
    id: "standing_hip_extension",
    name: "Standing Hip Extension",
    equipment: ["chair"],
    pattern: "isolation",
    muscles: ["Glutes", "Hamstrings"],
    compound: false,
    level: 1,
    unit: "reps",
    loadable: true,
    loads: ["hip"],
    lowImpact: true,
    substitutes: ["glute_bridge", "band_hip_thrust"],
    cues: [
      "Hold the chair back and take one straight leg back behind you, squeezing your bottom.",
      "Stay upright: the leg only goes as far as it can without your back arching.",
    ],
  },
  {
    id: "low_step_up",
    name: "Stair Step-up",
    equipment: ["bodyweight"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "reps",
    loadable: true,
    loads: ["knee", "hip"],
    lowImpact: true,
    substitutes: ["step_up_bw", "supported_split_squat"],
    cues: [
      "Step up onto the bottom stair, or a sturdy low step, with a hand on the rail or a wall.",

      "Lead with the same leg for the whole set, then swap. Down is where to take your time.",
    ],
  },
  {
    id: "supported_split_squat",
    name: "Supported Split Squat",
    equipment: ["chair"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "reps",
    loadable: true,
    loads: ["knee", "hip"],
    lowImpact: true,
    harder: "split_squat_bw",
    substitutes: ["low_step_up", "reverse_lunge_bw"],
    cues: [
      "Hold the chair back, one foot a long step behind the other.",
      "Bend both knees to lower a little, then stand. Only go as low as feels steady.",
    ],
  },
  {
    id: "seated_band_chest_press",
    name: "Seated Band Chest Press",
    equipment: ["chair", "bands"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["shoulder", "elbow"],
    lowImpact: true,
    substitutes: ["band_chest_press", "wall_pushup"],
    cues: [
      "Band around the chair back and under your arms, a handle in each hand.",
      "Press straight out at chest height, then let the band bring your hands back slowly.",
    ],
  },
  {
    id: "seated_band_leg_press",
    name: "Seated Band Leg Press",
    equipment: ["chair", "bands"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["knee", "hip"],
    lowImpact: true,
    harder: "sit_to_stand",
    substitutes: ["leg_press", "sit_to_stand_assisted"],
    cues: [
      "Sit tall, loop the band around one foot and hold the ends by your hips.",
      "Knee up to your chest, then push the foot straight out against the band.",
    ],
  },
  {
    id: "seated_band_abduction",
    name: "Seated Band Hip Abduction",
    equipment: ["chair", "bands"],
    pattern: "isolation",
    muscles: ["Glutes"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["hip"],
    lowImpact: true,
    substitutes: ["standing_hip_abduction", "band_lateral_walk"],
    cues: [
      "Band just above your knees, feet flat.",
      "Push the knees apart, pause, and let them come back slowly.",
    ],
  },

];
