import type { ExerciseDef } from "./types";

/**
 * Mobility and flexibility. Used for warm-ups, cool-downs, and as the bulk of
 * a session for the general-health goal, where the aim is moving well rather
 * than lifting more.
 */
export const MOBILITY_EXERCISES: ExerciseDef[] = [
  {
    id: "cat_cow",
    name: "Cat-Cow",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Spine", "Core"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: [],
    lowImpact: true,
    cues: ["Alternate arching and rounding, moving with your breath."],
  },
  {
    id: "hip_flexor_stretch",
    name: "Kneeling Hip Flexor Stretch",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Hip flexors"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["knee", "hip"],
    lowImpact: true,
    cues: ["Tuck your tailbone under before leaning forward — that's where the stretch comes from."],
  },
  {
    id: "hamstring_stretch",
    name: "Hamstring Stretch",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Hamstrings"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["hip"],
    lowImpact: true,
  },
  {
    id: "worlds_greatest_stretch",
    name: "World's Greatest Stretch",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Hips", "Thoracic spine", "Hamstrings"],
    compound: true,
    level: 2,
    unit: "reps",
    loads: ["hip", "shoulder"],
    cues: ["Lunge, drop the elbow inside the front foot, then rotate open."],
  },
  {
    id: "thoracic_rotation",
    name: "Thoracic Rotation",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Thoracic spine"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["spine"],
    lowImpact: true,
    cues: ["On all fours, hand behind your head, rotate the elbow up to the ceiling."],
  },
  {
    id: "shoulder_dislocate",
    name: "Band Shoulder Pass-Through",
    equipment: ["bands"],
    pattern: "mobility",
    muscles: ["Shoulders", "Chest"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["shoulder"],
    lowImpact: true,
    cues: ["Wide grip, straight arms, over and behind slowly.", "Widen the grip if it pinches."],
  },
  {
    id: "ankle_mobilisation",
    name: "Ankle Mobilisation",
    equipment: ["bodyweight"],
    pattern: "mobility",
    muscles: ["Ankles", "Calves"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["ankle"],
    lowImpact: true,
    cues: ["Knee travels forward over the toes with the heel down. Helps squat depth."],
  },
  {
    id: "ninety_ninety",
    name: "90/90 Hip Switch",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Hips"],
    compound: false,
    level: 2,
    unit: "reps",
    loads: ["hip", "knee"],
    lowImpact: true,
    cues: ["Both knees at right angles, rotate side to side without using your hands."],
  },
  {
    id: "childs_pose",
    name: "Child's Pose",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Lats", "Spine", "Hips"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["knee"],
    lowImpact: true,
  },
  {
    id: "couch_stretch",
    name: "Couch Stretch",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Quads", "Hip flexors"],
    compound: false,
    level: 2,
    unit: "time",
    loads: ["knee", "hip"],
    cues: ["Back foot up against a wall or sofa. Intense — ease into it."],
  },
  {
    id: "pec_doorway_stretch",
    name: "Doorway Chest Stretch",
    equipment: ["bodyweight"],
    pattern: "mobility",
    muscles: ["Chest", "Front delts"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["shoulder"],
    lowImpact: true,
  },
  {
    id: "neck_rotation",
    name: "Neck Rotation",
    equipment: ["bodyweight"],
    pattern: "mobility",
    muscles: ["Neck"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["neck"],
    lowImpact: true,
    cues: ["Slow and small. Never force range at the neck."],
  },
  {
    id: "glute_stretch",
    name: "Figure-Four Glute Stretch",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Glutes"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["hip"],
    lowImpact: true,
  },
  {
    id: "dynamic_leg_swing",
    name: "Leg Swings",
    equipment: ["chair"],
    pattern: "mobility",
    muscles: ["Hips", "Hamstrings"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["hip"],
    lowImpact: true,
    cues: ["Hold something for balance. Front to back, then side to side."],
  },
  {
    id: "arm_circles",
    name: "Arm Circles",
    equipment: ["bodyweight"],
    pattern: "mobility",
    muscles: ["Shoulders"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["shoulder"],
    lowImpact: true,
  },
];
