import type { ExerciseDef } from "./types";

/**
 * Mobility and flexibility. Used for warm-ups, cool-downs, and as the bulk of
 * a session for the general-health goal, where the aim is moving well rather
 * than lifting more.
 */
export const MOBILITY_EXERCISES: ExerciseDef[] = [
  {
    id: "cat_cow",
    name: "Cat-Cow",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Spine", "Core"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: [],
    lowImpact: true,
    cues: ["Alternate arching and rounding, moving with your breath."],
  },
  {
    id: "hip_flexor_stretch",
    name: "Kneeling Hip Flexor Stretch",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Hip flexors"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["knee", "hip"],
    lowImpact: true,
    cues: ["Tuck your tailbone under before leaning forward — that's where the stretch comes from."],
  },
  {
    id: "hamstring_stretch",
    name: "Hamstring Stretch",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Hamstrings"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["hip"],
    lowImpact: true,
    cues: ["Lie on your back, one leg up, a towel around the foot if you need it.", "Keep the knee almost straight and ease the leg toward you."],
  },
  {
    id: "worlds_greatest_stretch",
    name: "World's Greatest Stretch",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Hips", "Thoracic spine", "Hamstrings"],
    compound: true,
    level: 2,
    unit: "reps",
    loads: ["hip", "shoulder"],
    cues: ["Lunge, drop the elbow inside the front foot, then rotate open."],
  },
  {
    id: "thoracic_rotation",
    name: "Thoracic Rotation",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Thoracic spine"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["spine"],
    lowImpact: true,
    cues: ["On all fours, hand behind your head, rotate the elbow up to the ceiling."],
  },
  {
    id: "shoulder_dislocate",
    name: "Band Shoulder Pass-Through",
    equipment: ["bands"],
    pattern: "mobility",
    muscles: ["Shoulders", "Chest"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["shoulder"],
    lowImpact: true,
    cues: ["Wide grip, straight arms, over and behind slowly.", "Widen the grip if it pinches."],
  },
  {
    id: "ankle_mobilisation",
    name: "Ankle Mobilisation",
    equipment: ["bodyweight"],
    pattern: "mobility",
    muscles: ["Ankles", "Calves"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["ankle"],
    lowImpact: true,
    cues: ["Knee travels forward over the toes with the heel down. Helps squat depth."],
  },
  {
    id: "ninety_ninety",
    name: "90/90 Hip Switch",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Hips"],
    compound: false,
    level: 2,
    unit: "reps",
    loads: ["hip", "knee"],
    lowImpact: true,
    cues: ["Both knees at right angles, rotate side to side without using your hands."],
  },
  {
    id: "childs_pose",
    name: "Child's Pose",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Lats", "Spine", "Hips"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["knee"],
    lowImpact: true,
    cues: ["Kneel, sit back on your heels and walk your hands forward.", "Let your forehead rest and breathe slowly."],
  },
  {
    id: "couch_stretch",
    name: "Couch Stretch",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Quads", "Hip flexors"],
    compound: false,
    level: 2,
    unit: "time",
    loads: ["knee", "hip"],
    cues: ["Back foot up against a wall or sofa. Intense — ease into it."],
  },
  {
    id: "pec_doorway_stretch",
    name: "Doorway Chest Stretch",
    equipment: ["bodyweight"],
    pattern: "mobility",
    muscles: ["Chest", "Front delts"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["shoulder"],
    lowImpact: true,
    cues: ["Forearm on a door frame, elbow at shoulder height.", "Step through gently until you feel the stretch across the chest."],
  },
  {
    id: "neck_rotation",
    name: "Neck Rotation",
    equipment: ["bodyweight"],
    pattern: "mobility",
    muscles: ["Neck"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["neck"],
    lowImpact: true,
    cues: ["Slow and small. Never force range at the neck."],
  },
  {
    id: "glute_stretch",
    name: "Figure-Four Glute Stretch",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Glutes"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["hip"],
    lowImpact: true,
    cues: ["Lie on your back, one ankle crossed over the other knee.", "Pull the bottom thigh toward you until the outer hip stretches."],
  },
  {
    id: "dynamic_leg_swing",
    name: "Leg Swings",
    equipment: ["chair"],
    pattern: "mobility",
    muscles: ["Hips", "Hamstrings"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["hip"],
    lowImpact: true,
    cues: ["Hold something for balance. Front to back, then side to side."],
  },
  {
    id: "arm_circles",
    name: "Arm Circles",
    equipment: ["bodyweight"],
    pattern: "mobility",
    muscles: ["Shoulders"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["shoulder"],
    lowImpact: true,
    cues: ["Arms out to the sides, start with small circles.", "Make them bigger, then reverse the direction."],
  },

  /*
   * Seated and standing versions of the stretches above, so a warm-up or a
   * mobility slot never has to start with getting down to the floor.
   */
  {
    id: "seated_hamstring_stretch",
    name: "Seated Hamstring Stretch",
    equipment: ["chair"],
    pattern: "mobility",
    muscles: ["Hamstrings"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["hip"],
    lowImpact: true,
    substitutes: ["hamstring_stretch"],
    cues: ["Sit near the front of the chair, one leg straight with the heel on the floor.", "Lean forward from the hips with a straight back until you feel the stretch."],
  },
  {
    id: "standing_calf_stretch",
    name: "Standing Calf Stretch",
    equipment: ["bodyweight"],
    pattern: "mobility",
    muscles: ["Calves", "Ankles"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["ankle"],
    lowImpact: true,
    cues: ["Hands on a wall, one foot back with the heel pressed down.", "Bend the front knee until you feel the stretch in the back calf."],
  },
  {
    id: "standing_quad_stretch",
    name: "Standing Quad Stretch",
    equipment: ["chair"],
    pattern: "mobility",
    muscles: ["Quads", "Hip flexors"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["knee"],
    lowImpact: true,
    substitutes: ["couch_stretch"],
    cues: ["Hold the chair, bend one knee and take hold of the ankle behind you.", "Knees side by side. A towel round the ankle helps if you can't reach."],
  },
  {
    id: "seated_figure_four",
    name: "Seated Figure-Four Stretch",
    equipment: ["chair"],
    pattern: "mobility",
    muscles: ["Glutes", "Hips"],
    compound: false,
    level: 1,
    unit: "time",
    loads: ["hip", "knee"],
    lowImpact: true,
    substitutes: ["glute_stretch"],
    cues: ["Sit tall and rest one ankle on the opposite knee.", "Lean forward gently with a straight back until the outer hip stretches."],
  },
  {
    id: "seated_ankle_circles",
    name: "Seated Ankle Circles",
    equipment: ["chair"],
    pattern: "mobility",
    muscles: ["Ankles", "Calves"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: [],
    lowImpact: true,
    substitutes: ["ankle_mobilisation"],
    cues: ["Lift one foot and draw slow, big circles with your toes, each side.", "Then point and flex the foot a few times."],
  },
  {
    id: "standing_hip_circles",
    name: "Standing Hip Circles",
    equipment: ["chair"],
    pattern: "mobility",
    muscles: ["Hips", "Glutes"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["hip"],
    lowImpact: true,
    substitutes: ["dynamic_leg_swing"],
    cues: ["Hold the chair, lift one knee and draw a slow circle out to the side and back.", "Small circles are fine; do each side."],
  },
  {
    id: "chin_tuck",
    name: "Chin Tuck",
    equipment: ["bodyweight"],
    pattern: "mobility",
    muscles: ["Neck", "Upper back"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["neck"],
    lowImpact: true,
    cues: ["Sit or stand tall and glide your chin straight back, making a double chin.", "Hold for a breath, relax. It's a small movement."],
  },
  {
    id: "open_book",
    name: "Open Book Stretch",
    equipment: ["mat"],
    pattern: "mobility",
    muscles: ["Thoracic spine", "Chest"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["spine", "shoulder"],
    lowImpact: true,
    substitutes: ["thoracic_rotation"],
    cues: ["Lie on your side, knees bent, arms out together in front.", "Open the top arm across to the other side, following it with your eyes, then close."],
  },
];
