import type { ExerciseDef } from "./types";

/** Loaded gym work: barbell, dumbbell, kettlebell, cable and machine movements. */
export const STRENGTH_EXERCISES: ExerciseDef[] = [
  // ---- horizontal push ----
  {
    id: "bench_press",
    name: "Barbell Bench Press",
    equipment: ["barbell", "bench"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps", "Front delts"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["shoulder", "elbow", "wrist"],
    substitutes: ["db_bench", "machine_chest_press", "pushup"],
    cues: [
      "Pull your shoulder blades together and down into the bench.",
      "Lower to mid-chest with control.",
      "Drive through your feet, not just your arms.",
    ],
  },
  {
    id: "incline_bench",
    name: "Incline Barbell Press",
    equipment: ["barbell", "bench"],
    pattern: "horizontal_push",
    muscles: ["Upper chest", "Triceps", "Front delts"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["shoulder", "elbow", "wrist"],
    substitutes: ["incline_db", "bench_press"],
    cues: ["Bench set around 30 degrees.", "Bar path finishes over your collarbone, not your face."],
  },
  {
    id: "db_bench",
    name: "Dumbbell Bench Press",
    equipment: ["dumbbell", "bench"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps", "Front delts"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder", "elbow", "wrist"],
    substitutes: ["bench_press", "machine_chest_press", "pushup"],
    cues: ["Keep wrists stacked over elbows.", "Let the dumbbells travel slightly inward at the top."],
  },
  {
    id: "incline_db",
    name: "Incline Dumbbell Press",
    equipment: ["dumbbell", "bench"],
    pattern: "horizontal_push",
    muscles: ["Upper chest", "Front delts", "Triceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder", "elbow", "wrist"],
    substitutes: ["incline_bench", "db_bench"],
    cues: ["Bench at 30-45 degrees.", "Don't flare the elbows past 75 degrees."],
  },
  {
    id: "db_floor_press",
    name: "Dumbbell Floor Press",
    equipment: ["dumbbell"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow", "wrist"],
    substitutes: ["db_bench", "pushup"],
    cues: ["The floor limits your range, which is often kinder on the shoulder."],
  },
  {
    id: "machine_chest_press",
    name: "Machine Chest Press",
    equipment: ["machine"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder", "elbow"],
    lowImpact: true,
    substitutes: ["db_bench", "bench_press"],
    cues: ["Set the seat so the handles sit at mid-chest."],
  },
  {
    id: "cable_fly",
    name: "Cable Fly",
    equipment: ["cable"],
    pattern: "isolation",
    muscles: ["Chest"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder"],
    cues: ["Soft bend in the elbows, held throughout."],
  },

  // ---- vertical push ----
  {
    id: "overhead_press",
    name: "Barbell Overhead Press",
    equipment: ["barbell"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Triceps"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["shoulder", "elbow", "wrist", "spine"],
    substitutes: ["db_shoulder_press", "machine_shoulder_press"],
    cues: ["Squeeze glutes to stop your lower back arching.", "Move your head back out of the bar path, then through at the top."],
  },
  {
    id: "db_shoulder_press",
    name: "Dumbbell Shoulder Press",
    equipment: ["dumbbell"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Triceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder", "elbow", "wrist"],
    substitutes: ["overhead_press", "machine_shoulder_press", "pike_pushup"],
    cues: ["Start at ear height and press without banging the dumbbells together."],
  },
  {
    id: "machine_shoulder_press",
    name: "Machine Shoulder Press",
    equipment: ["machine"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Triceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder", "elbow"],
    lowImpact: true,
    substitutes: ["db_shoulder_press"],
  },
  {
    id: "kb_press",
    name: "Kettlebell Overhead Press",
    equipment: ["kettlebell"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Triceps"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["shoulder", "elbow", "wrist"],
    substitutes: ["db_shoulder_press"],
    cues: ["The bell rests on the back of the forearm in the rack position."],
  },
  {
    id: "landmine_press",
    name: "Landmine Press",
    equipment: ["barbell"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Upper chest", "Triceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder", "elbow"],
    lowImpact: true,
    substitutes: ["db_shoulder_press"],
    cues: ["The angled path is often comfortable when full overhead work isn't."],
  },

  // ---- horizontal pull ----
  {
    id: "barbell_row",
    name: "Barbell Row",
    equipment: ["barbell"],
    pattern: "horizontal_pull",
    muscles: ["Lats", "Upper back", "Biceps"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["spine", "elbow"],
    substitutes: ["db_row", "cable_row", "machine_row"],
    cues: ["Hinge to around 45 degrees and hold that position.", "Pull to your stomach, not your chest."],
  },
  {
    id: "db_row",
    name: "Dumbbell Row",
    equipment: ["dumbbell"],
    pattern: "horizontal_pull",
    muscles: ["Lats", "Upper back", "Biceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    substitutes: ["cable_row", "machine_row", "inverted_row"],
    cues: ["Support yourself on a bench.", "Lead with the elbow, finishing near your hip."],
  },
  {
    id: "cable_row",
    name: "Seated Cable Row",
    equipment: ["cable"],
    pattern: "horizontal_pull",
    muscles: ["Lats", "Upper back", "Biceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    lowImpact: true,
    substitutes: ["machine_row", "db_row"],
    cues: ["Sit tall; avoid rocking back and forth to move the weight."],
  },
  {
    id: "machine_row",
    name: "Machine Row",
    equipment: ["machine"],
    pattern: "horizontal_pull",
    muscles: ["Lats", "Upper back", "Biceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    lowImpact: true,
    substitutes: ["cable_row", "db_row"],
  },
  {
    id: "kb_row",
    name: "Kettlebell Row",
    equipment: ["kettlebell"],
    pattern: "horizontal_pull",
    muscles: ["Lats", "Upper back", "Biceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    substitutes: ["db_row"],
  },
  {
    id: "chest_supported_row",
    name: "Chest-Supported Row",
    equipment: ["dumbbell", "bench"],
    pattern: "horizontal_pull",
    muscles: ["Upper back", "Lats", "Rear delts"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    lowImpact: true,
    substitutes: ["db_row", "machine_row"],
    cues: ["Chest on an incline bench takes the lower back out of it entirely."],
  },

  // ---- vertical pull ----
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    equipment: ["cable"],
    pattern: "vertical_pull",
    muscles: ["Lats", "Biceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    lowImpact: true,
    substitutes: ["machine_pulldown", "pullup", "band_pulldown"],
    cues: ["Lead with your elbows.", "Avoid leaning far back to muscle the weight down."],
  },
  {
    id: "machine_pulldown",
    name: "Machine Pulldown",
    equipment: ["machine"],
    pattern: "vertical_pull",
    muscles: ["Lats", "Biceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    lowImpact: true,
    substitutes: ["lat_pulldown"],
  },

  // ---- squat ----
  {
    id: "back_squat",
    name: "Back Squat",
    equipment: ["barbell", "squat_rack"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["knee", "hip", "spine"],
    substitutes: ["front_squat", "goblet_squat", "leg_press"],
    cues: ["Brace your stomach before you unrack.", "Sit between your hips, knees tracking over your toes."],
  },
  {
    id: "front_squat",
    name: "Front Squat",
    equipment: ["barbell", "squat_rack"],
    pattern: "squat",
    muscles: ["Quads", "Core"],
    compound: true,
    level: 3,
    unit: "weight_reps",
    loads: ["knee", "hip", "spine", "wrist"],
    substitutes: ["back_squat", "goblet_squat"],
    cues: ["Elbows high throughout — if they drop, the bar follows."],
  },
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    equipment: ["dumbbell"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    substitutes: ["kb_goblet_squat", "leg_press", "bw_squat"],
    cues: ["Hold the weight at your chest.", "The counterweight makes it easier to stay upright."],
  },
  {
    id: "kb_goblet_squat",
    name: "Kettlebell Goblet Squat",
    equipment: ["kettlebell"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    substitutes: ["goblet_squat"],
  },
  {
    id: "leg_press",
    name: "Leg Press",
    equipment: ["machine"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    lowImpact: true,
    substitutes: ["hack_squat", "goblet_squat"],
    cues: ["Don't let your lower back round off the pad at the bottom."],
  },
  {
    id: "hack_squat",
    name: "Hack Squat",
    equipment: ["machine"],
    pattern: "squat",
    muscles: ["Quads"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    substitutes: ["leg_press", "back_squat"],
  },

  // ---- hinge ----
  {
    id: "deadlift",
    name: "Deadlift",
    equipment: ["barbell"],
    pattern: "hinge",
    muscles: ["Hamstrings", "Glutes", "Back"],
    compound: true,
    level: 3,
    unit: "weight_reps",
    loads: ["spine", "hip", "knee"],
    substitutes: ["rdl", "hip_thrust", "kb_swing"],
    cues: ["Bar stays close to your legs the whole way.", "Push the floor away rather than yanking the bar up."],
  },
  {
    id: "rdl",
    name: "Romanian Deadlift",
    equipment: ["barbell"],
    pattern: "hinge",
    muscles: ["Hamstrings", "Glutes"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["spine", "hip"],
    substitutes: ["db_rdl", "single_leg_rdl_bw"],
    cues: ["Soft knees, push the hips back.", "Stop when your back would otherwise start rounding."],
  },
  {
    id: "db_rdl",
    name: "Dumbbell Romanian Deadlift",
    equipment: ["dumbbell"],
    pattern: "hinge",
    muscles: ["Hamstrings", "Glutes"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["spine", "hip"],
    substitutes: ["rdl", "single_leg_rdl_bw"],
  },
  {
    id: "kb_swing",
    name: "Kettlebell Swing",
    equipment: ["kettlebell"],
    pattern: "hinge",
    muscles: ["Hamstrings", "Glutes", "Core"],
    compound: true,
    level: 2,
    unit: "reps",
    loads: ["spine", "hip", "shoulder"],
    substitutes: ["rdl", "hip_thrust"],
    cues: ["This is a hip snap, not a squat and not a front raise.", "The bell floats up; you don't lift it with your arms."],
  },
  {
    id: "hip_thrust",
    name: "Hip Thrust",
    equipment: ["barbell", "bench"],
    pattern: "hinge",
    muscles: ["Glutes", "Hamstrings"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["hip", "spine"],
    substitutes: ["glute_bridge", "single_leg_glute_bridge"],
    cues: ["Tuck your chin and ribs down as you drive up.", "Finish with hips level, not hyperextended."],
  },
  {
    id: "back_extension",
    name: "Back Extension",
    equipment: ["machine"],
    pattern: "hinge",
    muscles: ["Lower back", "Glutes"],
    compound: false,
    level: 1,
    unit: "reps",
    loads: ["spine"],
    lowImpact: true,
    substitutes: ["back_extension_bw"],
  },

  // ---- lunge ----
  {
    id: "walking_lunge",
    name: "Walking Lunge",
    equipment: ["dumbbell"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    substitutes: ["walking_lunge_bw", "split_squat"],
  },
  {
    id: "split_squat",
    name: "Bulgarian Split Squat",
    equipment: ["dumbbell", "bench"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    substitutes: ["bulgarian_split_squat_bw", "walking_lunge"],
    cues: ["Rear foot on the bench, most of the weight through the front heel."],
  },
  {
    id: "step_up",
    name: "Step-up",
    equipment: ["dumbbell", "bench"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    substitutes: ["step_up_bw"],
  },

  // ---- carry ----
  {
    id: "farmers_carry",
    name: "Farmer's Carry",
    equipment: ["dumbbell"],
    pattern: "carry",
    muscles: ["Core", "Forearms", "Upper back"],
    compound: true,
    level: 1,
    unit: "distance",
    loads: ["spine", "shoulder", "wrist"],
    cues: ["Stand tall, shoulders back, walk normally.", "Grip usually gives out first — that's fine."],
  },
  {
    id: "suitcase_carry",
    name: "Suitcase Carry",
    equipment: ["kettlebell"],
    pattern: "carry",
    muscles: ["Obliques", "Core", "Forearms"],
    compound: true,
    level: 1,
    unit: "distance",
    loads: ["spine", "shoulder"],
    substitutes: ["farmers_carry"],
    cues: ["Weight in one hand only. Resist leaning toward it."],
  },

  // ---- isolation ----
  {
    id: "lateral_raise",
    name: "Lateral Raise",
    equipment: ["dumbbell"],
    pattern: "isolation",
    muscles: ["Side delts"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder"],
    substitutes: ["cable_lateral_raise", "band_lateral_raise"],
    cues: ["Lead with the elbows, stop at shoulder height."],
  },
  {
    id: "cable_lateral_raise",
    name: "Cable Lateral Raise",
    equipment: ["cable"],
    pattern: "isolation",
    muscles: ["Side delts"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder"],
    substitutes: ["lateral_raise"],
  },
  {
    id: "face_pull",
    name: "Face Pull",
    equipment: ["cable"],
    pattern: "isolation",
    muscles: ["Rear delts", "Upper back"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: [],
    lowImpact: true,
    substitutes: ["rear_delt_fly", "band_face_pull"],
    cues: ["Pull toward your forehead, hands finishing wide."],
  },
  {
    id: "rear_delt_fly",
    name: "Rear Delt Fly",
    equipment: ["dumbbell"],
    pattern: "isolation",
    muscles: ["Rear delts"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: [],
    substitutes: ["face_pull"],
  },
  {
    id: "db_curl",
    name: "Dumbbell Curl",
    equipment: ["dumbbell"],
    pattern: "isolation",
    muscles: ["Biceps"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    substitutes: ["barbell_curl", "band_curl", "hammer_curl"],
  },
  {
    id: "hammer_curl",
    name: "Hammer Curl",
    equipment: ["dumbbell"],
    pattern: "isolation",
    muscles: ["Biceps", "Forearms"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    substitutes: ["db_curl"],
  },
  {
    id: "barbell_curl",
    name: "Barbell Curl",
    equipment: ["barbell"],
    pattern: "isolation",
    muscles: ["Biceps"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow", "wrist"],
    substitutes: ["db_curl"],
  },
  {
    id: "triceps_pushdown",
    name: "Triceps Pushdown",
    equipment: ["cable"],
    pattern: "isolation",
    muscles: ["Triceps"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    substitutes: ["overhead_extension", "bench_dip"],
    cues: ["Elbows pinned to your sides.", "Control the way back up."],
  },
  {
    id: "overhead_extension",
    name: "Overhead Triceps Extension",
    equipment: ["dumbbell"],
    pattern: "isolation",
    muscles: ["Triceps"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow", "shoulder"],
    substitutes: ["triceps_pushdown"],
  },
  {
    id: "leg_curl",
    name: "Leg Curl",
    equipment: ["machine"],
    pattern: "isolation",
    muscles: ["Hamstrings"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["knee"],
    lowImpact: true,
    substitutes: ["nordic_negative"],
  },
  {
    id: "leg_extension",
    name: "Leg Extension",
    equipment: ["machine"],
    pattern: "isolation",
    muscles: ["Quads"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["knee"],
    lowImpact: true,
  },
  {
    id: "db_calf_raise",
    name: "Dumbbell Calf Raise",
    equipment: ["dumbbell"],
    pattern: "isolation",
    muscles: ["Calves"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["ankle"],
    substitutes: ["calf_raise"],
  },
  {
    id: "cable_crunch",
    name: "Cable Crunch",
    equipment: ["cable"],
    pattern: "core",
    muscles: ["Core"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["spine"],
    substitutes: ["hanging_knee_raise", "plank"],
  },
];
