import type { ExerciseDef } from "./types";

/** Loaded gym work: barbell, dumbbell, kettlebell, cable and machine movements. */
export const STRENGTH_EXERCISES: ExerciseDef[] = [
  // ---- horizontal push ----
  {
    id: "bench_press",
    name: "Barbell Bench Press",
    equipment: ["barbell", "bench"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps", "Front delts"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["shoulder", "elbow", "wrist"],
    substitutes: ["db_bench", "machine_chest_press", "pushup"],
    cues: [
      "Pull your shoulder blades together and down into the bench.",
      "Lower to mid-chest with control.",
      "Drive through your feet, not just your arms.",
    ],
  },
  {
    id: "incline_bench",
    name: "Incline Barbell Press",
    equipment: ["barbell", "bench"],
    pattern: "horizontal_push",
    muscles: ["Upper chest", "Triceps", "Front delts"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["shoulder", "elbow", "wrist"],
    substitutes: ["incline_db", "bench_press"],
    cues: ["Bench set around 30 degrees.", "Bar path finishes over your collarbone, not your face."],
  },
  {
    id: "db_bench",
    name: "Dumbbell Bench Press",
    equipment: ["dumbbell", "bench"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps", "Front delts"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder", "elbow", "wrist"],
    substitutes: ["bench_press", "machine_chest_press", "pushup"],
    cues: ["Keep wrists stacked over elbows.", "Let the dumbbells travel slightly inward at the top."],
  },
  {
    id: "incline_db",
    name: "Incline Dumbbell Press",
    equipment: ["dumbbell", "bench"],
    pattern: "horizontal_push",
    muscles: ["Upper chest", "Front delts", "Triceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder", "elbow", "wrist"],
    substitutes: ["incline_bench", "db_bench"],
    cues: ["Bench at 30-45 degrees.", "Don't flare the elbows past 75 degrees."],
  },
  {
    id: "db_floor_press",
    name: "Dumbbell Floor Press",
    equipment: ["dumbbell"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow", "wrist"],
    floor: true,
    substitutes: ["db_bench", "pushup"],
    cues: ["The floor limits your range, which is often kinder on the shoulder."],
  },
  {
    id: "machine_chest_press",
    name: "Machine Chest Press",
    equipment: ["machine"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder", "elbow"],
    lowImpact: true,
    substitutes: ["db_bench", "bench_press"],
    cues: ["Set the seat so the handles sit at mid-chest."],
  },
  {
    id: "cable_fly",
    name: "Cable Fly",
    equipment: ["cable"],
    pattern: "isolation",
    muscles: ["Chest"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder"],
    cues: ["Soft bend in the elbows, held throughout."],
  },

  // ---- vertical push ----
  {
    id: "overhead_press",
    name: "Barbell Overhead Press",
    equipment: ["barbell"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Triceps"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["shoulder", "elbow", "wrist", "spine"],
    substitutes: ["db_shoulder_press", "machine_shoulder_press"],
    cues: ["Squeeze glutes to stop your lower back arching.", "Move your head back out of the bar path, then through at the top."],
  },
  {
    id: "db_shoulder_press",
    name: "Dumbbell Shoulder Press",
    equipment: ["dumbbell"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Triceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder", "elbow", "wrist"],
    substitutes: ["overhead_press", "machine_shoulder_press", "pike_pushup"],
    cues: ["Start at ear height and press without banging the dumbbells together."],
  },
  {
    id: "machine_shoulder_press",
    name: "Machine Shoulder Press",
    equipment: ["machine"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Triceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder", "elbow"],
    lowImpact: true,
    substitutes: ["db_shoulder_press"],
    cues: ["Set the seat so the handles start at shoulder height.", "Press up without shrugging, then lower under control."],
  },
  {
    id: "kb_press",
    name: "Kettlebell Overhead Press",
    equipment: ["kettlebell"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Triceps"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["shoulder", "elbow", "wrist"],
    substitutes: ["db_shoulder_press"],
    cues: ["The bell rests on the back of the forearm in the rack position."],
  },
  {
    id: "landmine_press",
    name: "Landmine Press",
    equipment: ["barbell"],
    pattern: "vertical_push",
    muscles: ["Shoulders", "Upper chest", "Triceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder", "elbow"],
    lowImpact: true,
    substitutes: ["db_shoulder_press"],
    cues: ["The angled path is often comfortable when full overhead work isn't."],
  },

  // ---- horizontal pull ----
  {
    id: "barbell_row",
    name: "Barbell Row",
    equipment: ["barbell"],
    pattern: "horizontal_pull",
    muscles: ["Lats", "Upper back", "Biceps"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["spine", "elbow"],
    substitutes: ["db_row", "cable_row", "machine_row"],
    cues: ["Hinge to around 45 degrees and hold that position.", "Pull to your stomach, not your chest."],
  },
  {
    id: "db_row",
    name: "Dumbbell Row",
    equipment: ["dumbbell"],
    pattern: "horizontal_pull",
    muscles: ["Lats", "Upper back", "Biceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    substitutes: ["cable_row", "machine_row", "inverted_row"],
    cues: ["Support yourself on a bench.", "Lead with the elbow, finishing near your hip."],
  },
  {
    id: "cable_row",
    name: "Seated Cable Row",
    equipment: ["cable"],
    pattern: "horizontal_pull",
    muscles: ["Lats", "Upper back", "Biceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    lowImpact: true,
    substitutes: ["machine_row", "db_row"],
    cues: ["Sit tall; avoid rocking back and forth to move the weight."],
  },
  {
    id: "machine_row",
    name: "Machine Row",
    equipment: ["machine"],
    pattern: "horizontal_pull",
    muscles: ["Lats", "Upper back", "Biceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    lowImpact: true,
    substitutes: ["cable_row", "db_row"],
    cues: ["Chest against the pad, pull the handles to your ribs.", "Squeeze the shoulder blades together before letting the weight back."],
  },
  {
    id: "kb_row",
    name: "Kettlebell Row",
    equipment: ["kettlebell"],
    pattern: "horizontal_pull",
    muscles: ["Lats", "Upper back", "Biceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    substitutes: ["db_row"],
    cues: ["One hand on a bench or your knee, back flat.", "Pull the kettlebell to your hip, elbow brushing your side."],
  },
  {
    id: "chest_supported_row",
    name: "Chest-Supported Row",
    equipment: ["dumbbell", "bench"],
    pattern: "horizontal_pull",
    muscles: ["Upper back", "Lats", "Rear delts"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    lowImpact: true,
    substitutes: ["db_row", "machine_row"],
    cues: ["Chest on an incline bench takes the lower back out of it entirely."],
  },

  // ---- vertical pull ----
  {
    id: "lat_pulldown",
    name: "Lat Pulldown",
    equipment: ["cable"],
    pattern: "vertical_pull",
    muscles: ["Lats", "Biceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    lowImpact: true,
    substitutes: ["machine_pulldown", "pullup", "band_pulldown"],
    cues: ["Lead with your elbows.", "Avoid leaning far back to muscle the weight down."],
  },
  {
    id: "machine_pulldown",
    name: "Machine Pulldown",
    equipment: ["machine"],
    pattern: "vertical_pull",
    muscles: ["Lats", "Biceps"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    lowImpact: true,
    substitutes: ["lat_pulldown"],
    cues: ["Pull the handles down to the top of your chest.", "Lean back only slightly and let the arms rise all the way."],
  },

  // ---- squat ----
  {
    id: "back_squat",
    name: "Back Squat",
    equipment: ["barbell", "squat_rack"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["knee", "hip", "spine"],
    substitutes: ["front_squat", "goblet_squat", "leg_press"],
    cues: ["Brace your stomach before you unrack.", "Sit between your hips, knees tracking over your toes."],
  },
  {
    id: "front_squat",
    name: "Front Squat",
    equipment: ["barbell", "squat_rack"],
    pattern: "squat",
    muscles: ["Quads", "Core"],
    compound: true,
    level: 3,
    unit: "weight_reps",
    loads: ["knee", "hip", "spine", "wrist"],
    substitutes: ["back_squat", "goblet_squat"],
    cues: ["Elbows high throughout — if they drop, the bar follows."],
  },
  {
    id: "goblet_squat",
    name: "Goblet Squat",
    equipment: ["dumbbell"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    substitutes: ["kb_goblet_squat", "leg_press", "bw_squat"],
    cues: ["Hold the weight at your chest.", "The counterweight makes it easier to stay upright."],
  },
  {
    id: "kb_goblet_squat",
    name: "Kettlebell Goblet Squat",
    equipment: ["kettlebell"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    substitutes: ["goblet_squat"],
    cues: ["Hold the kettlebell by the horns against your chest.", "Sit down between your heels, elbows inside the knees."],
  },
  {
    id: "leg_press",
    name: "Leg Press",
    equipment: ["machine"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    lowImpact: true,
    substitutes: ["hack_squat", "goblet_squat"],
    cues: ["Don't let your lower back round off the pad at the bottom."],
  },
  {
    id: "hack_squat",
    name: "Hack Squat",
    equipment: ["machine"],
    pattern: "squat",
    muscles: ["Quads"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    substitutes: ["leg_press", "back_squat"],
    cues: ["Back flat against the pad, feet shoulder-width on the platform.", "Lower until your thighs are about parallel, then drive up."],
  },

  // ---- hinge ----
  {
    id: "deadlift",
    name: "Deadlift",
    equipment: ["barbell"],
    pattern: "hinge",
    muscles: ["Hamstrings", "Glutes", "Back"],
    compound: true,
    level: 3,
    unit: "weight_reps",
    loads: ["spine", "hip", "knee"],
    substitutes: ["rdl", "hip_thrust", "kb_swing"],
    cues: ["Bar stays close to your legs the whole way.", "Push the floor away rather than yanking the bar up."],
  },
  {
    id: "rdl",
    name: "Romanian Deadlift",
    equipment: ["barbell"],
    pattern: "hinge",
    muscles: ["Hamstrings", "Glutes"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["spine", "hip"],
    substitutes: ["db_rdl", "single_leg_rdl_bw"],
    cues: ["Soft knees, push the hips back.", "Stop when your back would otherwise start rounding."],
  },
  {
    id: "db_rdl",
    name: "Dumbbell Romanian Deadlift",
    equipment: ["dumbbell"],
    pattern: "hinge",
    muscles: ["Hamstrings", "Glutes"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["spine", "hip"],
    substitutes: ["rdl", "single_leg_rdl_bw"],
    cues: ["Soft knees, push your hips back and slide the dumbbells down your thighs.", "Stop when your hamstrings are tight and your back is still flat."],
  },
  {
    id: "kb_swing",
    name: "Kettlebell Swing",
    equipment: ["kettlebell"],
    pattern: "hinge",
    muscles: ["Hamstrings", "Glutes", "Core"],
    compound: true,
    level: 2,
    // The bell is the load, not an addition to bodyweight, so it's recorded
    // the way any other lift is. Logged as reps alone, a 12 kg swing and a
    // 32 kg swing were the same entry.
    unit: "weight_reps",
    loads: ["spine", "hip", "shoulder"],
    substitutes: ["rdl", "hip_thrust"],
    cues: ["This is a hip snap, not a squat and not a front raise.", "The bell floats up; you don't lift it with your arms."],
  },
  {
    id: "hip_thrust",
    name: "Hip Thrust",
    equipment: ["barbell", "bench"],
    pattern: "hinge",
    muscles: ["Glutes", "Hamstrings"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["hip", "spine"],
    substitutes: ["glute_bridge", "single_leg_glute_bridge"],
    cues: ["Tuck your chin and ribs down as you drive up.", "Finish with hips level, not hyperextended."],
  },
  {
    id: "back_extension",
    name: "Back Extension",
    equipment: ["machine"],
    pattern: "hinge",
    muscles: ["Lower back", "Glutes"],
    compound: false,
    level: 1,
    unit: "reps",
    loadable: true,
    loads: ["spine"],
    lowImpact: true,
    substitutes: ["back_extension_bw"],
    cues: ["Hips on the pad, lower from the hips with a flat back.", "Rise until your body is in a straight line; no need to arch past it."],
  },

  // ---- lunge ----
  {
    id: "walking_lunge",
    name: "Walking Lunge",
    equipment: ["dumbbell"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    substitutes: ["walking_lunge_bw", "split_squat"],
    cues: ["Long steps, back knee toward the floor, torso tall.", "Push through the front heel into the next step."],
  },
  {
    id: "split_squat",
    name: "Bulgarian Split Squat",
    equipment: ["dumbbell", "bench"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    substitutes: ["bulgarian_split_squat_bw", "walking_lunge"],
    cues: ["Rear foot on the bench, most of the weight through the front heel."],
  },
  {
    id: "step_up",
    name: "Step-up",
    equipment: ["dumbbell", "bench"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    substitutes: ["step_up_bw"],
    cues: ["A step or bench that leaves your knee no higher than your hip.", "Push through the whole foot on the box; don't spring off the back leg."],
  },

  // ---- carry ----
  {
    id: "farmers_carry",
    name: "Farmer's Carry",
    equipment: ["dumbbell"],
    pattern: "carry",
    muscles: ["Core", "Forearms", "Upper back"],
    compound: true,
    level: 1,
    unit: "distance",
    loads: ["spine", "shoulder", "wrist"],
    cues: ["Stand tall, shoulders back, walk normally.", "Grip usually gives out first — that's fine."],
  },
  {
    id: "suitcase_carry",
    name: "Suitcase Carry",
    equipment: ["kettlebell"],
    pattern: "carry",
    muscles: ["Obliques", "Core", "Forearms"],
    compound: true,
    level: 1,
    unit: "distance",
    loads: ["spine", "shoulder"],
    substitutes: ["farmers_carry"],
    cues: ["Weight in one hand only. Resist leaning toward it."],
  },

  // ---- isolation ----
  {
    id: "lateral_raise",
    name: "Lateral Raise",
    equipment: ["dumbbell"],
    pattern: "isolation",
    muscles: ["Side delts"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder"],
    substitutes: ["cable_lateral_raise", "band_lateral_raise"],
    cues: ["Lead with the elbows, stop at shoulder height."],
  },
  {
    id: "cable_lateral_raise",
    name: "Cable Lateral Raise",
    equipment: ["cable"],
    pattern: "isolation",
    muscles: ["Side delts"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder"],
    substitutes: ["lateral_raise"],
    cues: ["Stand side-on, cable crossing in front of you.", "Lift out to the side until your hand is level with your shoulder."],
  },
  {
    id: "face_pull",
    name: "Face Pull",
    equipment: ["cable"],
    pattern: "isolation",
    muscles: ["Rear delts", "Upper back"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: [],
    lowImpact: true,
    substitutes: ["rear_delt_fly", "band_face_pull"],
    cues: ["Pull toward your forehead, hands finishing wide."],
  },
  {
    id: "rear_delt_fly",
    name: "Rear Delt Fly",
    equipment: ["dumbbell"],
    pattern: "isolation",
    muscles: ["Rear delts"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: [],
    substitutes: ["face_pull"],
    cues: ["Hinge forward with a flat back, dumbbells hanging below your chest.", "Sweep them out to the sides with soft elbows, leading with the elbows."],
  },
  {
    id: "db_curl",
    name: "Dumbbell Curl",
    equipment: ["dumbbell"],
    pattern: "isolation",
    muscles: ["Biceps"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    substitutes: ["barbell_curl", "band_curl", "hammer_curl"],
    cues: ["Elbows by your sides, curl without swinging.", "Lower all the way until your arms are straight."],
  },
  {
    id: "hammer_curl",
    name: "Hammer Curl",
    equipment: ["dumbbell"],
    pattern: "isolation",
    muscles: ["Biceps", "Forearms"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    substitutes: ["db_curl"],
    cues: ["Palms facing each other, like holding a hammer.", "Keep the elbows still; only the forearms move."],
  },
  {
    id: "barbell_curl",
    name: "Barbell Curl",
    equipment: ["barbell"],
    pattern: "isolation",
    muscles: ["Biceps"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow", "wrist"],
    substitutes: ["db_curl"],
    cues: ["Shoulder-width grip, elbows by your sides.", "No rocking: if you have to lean back, the bar is too heavy."],
  },
  {
    id: "triceps_pushdown",
    name: "Triceps Pushdown",
    equipment: ["cable"],
    pattern: "isolation",
    muscles: ["Triceps"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    substitutes: ["overhead_extension", "bench_dip"],
    cues: ["Elbows pinned to your sides.", "Control the way back up."],
  },
  {
    id: "overhead_extension",
    name: "Overhead Triceps Extension",
    equipment: ["dumbbell"],
    pattern: "isolation",
    muscles: ["Triceps"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow", "shoulder"],
    substitutes: ["triceps_pushdown"],
    cues: ["Hold one dumbbell with both hands overhead.", "Lower it behind your head by bending the elbows, then straighten."],
  },
  {
    id: "leg_curl",
    name: "Leg Curl",
    equipment: ["machine"],
    pattern: "isolation",
    muscles: ["Hamstrings"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["knee"],
    lowImpact: true,
    substitutes: ["nordic_negative"],
    cues: ["Line your knee up with the machine's pivot.", "Curl the pad as far as it goes, then lower slowly."],
  },
  {
    id: "leg_extension",
    name: "Leg Extension",
    equipment: ["machine"],
    pattern: "isolation",
    muscles: ["Quads"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["knee"],
    lowImpact: true,
    cues: ["Line your knee up with the machine's pivot, back against the seat.", "Straighten the legs, pause, and lower under control."],
  },
  {
    id: "db_calf_raise",
    name: "Dumbbell Calf Raise",
    equipment: ["dumbbell"],
    pattern: "isolation",
    muscles: ["Calves"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["ankle"],
    substitutes: ["calf_raise"],
    cues: ["Hold a dumbbell at your side, a hand on something for balance.", "Up as high as you can on your toes, pause, then lower slowly."],
  },
  {
    id: "cable_crunch",
    name: "Cable Crunch",
    equipment: ["cable"],
    pattern: "core",
    muscles: ["Core"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["spine"],
    substitutes: ["hanging_knee_raise", "plank"],
    cues: ["Kneel facing the cable, rope held beside your head.", "Curl your ribs toward your hips; the hips stay still."],
  },

  // ---- added: more ways to fill each slot ----
  {
    id: "close_grip_bench",
    name: "Close-Grip Bench Press",
    equipment: ["barbell", "bench"],
    pattern: "horizontal_push",
    muscles: ["Chest", "Triceps", "Front delts"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["shoulder", "elbow", "wrist"],
    substitutes: ["bench_press", "diamond_pushup"],
    cues: ["Hands just inside shoulder width, elbows tucked close to your sides.", "Touch the lower chest, then press back up over the shoulders."],
  },
  {
    id: "db_fly",
    name: "Dumbbell Fly",
    equipment: ["dumbbell", "bench"],
    pattern: "isolation",
    muscles: ["Chest", "Front delts"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder", "elbow"],
    substitutes: ["cable_fly", "pec_deck"],
    cues: ["A soft bend in the elbows that stays the same all the way down.", "Open until you feel a stretch across the chest, not a strain at the shoulder."],
  },
  {
    id: "pec_deck",
    name: "Machine Fly",
    equipment: ["machine"],
    pattern: "isolation",
    muscles: ["Chest", "Front delts"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder"],
    lowImpact: true,
    substitutes: ["cable_fly", "db_fly"],
    cues: ["Set the seat so the handles line up with your chest.", "Squeeze the handles together, then let them open slowly."],
  },
  {
    id: "assisted_pullup_machine",
    name: "Assisted Pull-up",
    equipment: ["machine"],
    pattern: "vertical_pull",
    muscles: ["Lats", "Biceps"],
    compound: true,
    level: 1,
    unit: "reps",
    loads: ["elbow"],
    lowImpact: true,
    harder: "pullup",
    substitutes: ["lat_pulldown", "band_assisted_pullup"],
    cues: [
      "Choose enough assistance to reach the top of the rep range with good form.",
      "Pull your chest toward the bar. As you get stronger, use less assistance.",
    ],
  },
  {
    id: "straight_arm_pulldown",
    name: "Straight-Arm Pulldown",
    equipment: ["cable"],
    pattern: "isolation",
    muscles: ["Lats"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["shoulder"],
    substitutes: ["db_pullover", "band_pulldown"],
    cues: ["Arms nearly straight, sweep the bar down to your thighs.", "Hinge forward a little and keep your ribs down; the lats do the work."],
  },
  {
    id: "db_pullover",
    name: "Dumbbell Pullover",
    equipment: ["dumbbell", "bench"],
    pattern: "isolation",
    muscles: ["Lats", "Chest"],
    compound: false,
    level: 2,
    unit: "weight_reps",
    loads: ["shoulder", "elbow"],
    substitutes: ["straight_arm_pulldown"],
    cues: ["Lie on the bench, one dumbbell held over your chest with both hands.", "Lower it back behind your head only as far as your shoulders are comfortable."],
  },
  {
    id: "reverse_pec_deck",
    name: "Reverse Machine Fly",
    equipment: ["machine"],
    pattern: "isolation",
    muscles: ["Rear delts", "Upper back"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: [],
    lowImpact: true,
    substitutes: ["face_pull", "rear_delt_fly", "band_pull_apart"],
    cues: ["Face the pad, arms out in front, and sweep them back in a wide arc.", "Lead with the elbows and stop when your arms are in line with your body."],
  },
  {
    id: "cable_curl",
    name: "Cable Curl",
    equipment: ["cable"],
    pattern: "isolation",
    muscles: ["Biceps"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    substitutes: ["db_curl", "band_curl"],
    cues: ["Elbows pinned by your sides; only the forearms move.", "The cable keeps tension at the bottom, so don't rush out of it."],
  },
  {
    id: "incline_db_curl",
    name: "Incline Dumbbell Curl",
    equipment: ["dumbbell", "bench"],
    pattern: "isolation",
    muscles: ["Biceps"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow", "shoulder"],
    substitutes: ["db_curl", "cable_curl"],
    cues: ["Sit back on a bench set to about 45 degrees, arms hanging straight down.", "Curl without letting the elbows drift forward."],
  },
  {
    id: "cable_overhead_extension",
    name: "Cable Overhead Triceps Extension",
    equipment: ["cable"],
    pattern: "isolation",
    muscles: ["Triceps"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow", "shoulder"],
    substitutes: ["overhead_extension", "triceps_pushdown"],
    cues: ["Face away from the cable with the rope behind your head.", "Elbows point forward and stay put; straighten the arms fully."],
  },
  {
    id: "db_skull_crusher",
    name: "Lying Dumbbell Triceps Extension",
    equipment: ["dumbbell", "bench"],
    pattern: "isolation",
    muscles: ["Triceps"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["elbow"],
    substitutes: ["overhead_extension", "triceps_pushdown"],
    cues: ["Lie on the bench, dumbbells over your shoulders, palms facing in.", "Bend only at the elbows to lower them beside your head, then straighten."],
  },
  {
    id: "db_box_squat",
    name: "Dumbbell Box Squat",
    equipment: ["dumbbell", "chair"],
    pattern: "squat",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    lowImpact: true,
    harder: "goblet_squat",
    substitutes: ["goblet_squat", "box_squat_bw"],
    cues: [
      "Hold a dumbbell at your chest and sit back until you lightly touch the chair.",
      "Don't settle or rock: touch and stand, pushing the floor away.",
    ],
  },
  {
    id: "db_split_squat",
    name: "Dumbbell Split Squat",
    equipment: ["dumbbell"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    harder: "split_squat",
    substitutes: ["split_squat_bw", "db_reverse_lunge"],
    cues: ["A long stance, feet staying where they are for the whole set.", "Drop the back knee straight down toward the floor, torso tall."],
  },
  {
    id: "db_reverse_lunge",
    name: "Dumbbell Reverse Lunge",
    equipment: ["dumbbell"],
    pattern: "lunge",
    muscles: ["Quads", "Glutes"],
    compound: true,
    level: 2,
    unit: "weight_reps",
    loads: ["knee", "hip"],
    easier: "db_split_squat",
    substitutes: ["walking_lunge", "reverse_lunge_bw"],
    cues: ["Step back into the lunge rather than forward — it's kinder on the knees.", "Push through the front foot to bring the back foot home."],
  },
  {
    id: "db_deadlift",
    name: "Dumbbell Deadlift",
    equipment: ["dumbbell"],
    pattern: "hinge",
    muscles: ["Glutes", "Hamstrings", "Quads"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["spine", "hip", "knee"],
    harder: "db_rdl",
    substitutes: ["kb_deadlift", "db_rdl"],
    cues: ["Dumbbells by your feet, hips back, flat back, then stand up tall.", "Keep the weights close to your legs the whole way."],
  },
  {
    id: "kb_deadlift",
    name: "Kettlebell Deadlift",
    equipment: ["kettlebell"],
    pattern: "hinge",
    muscles: ["Glutes", "Hamstrings", "Quads"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["spine", "hip", "knee"],
    harder: "kb_swing",
    substitutes: ["db_deadlift", "db_rdl"],
    cues: ["Kettlebell between your feet. Push your hips back, grip it, and stand up.", "The same lift as picking something up off the floor, done well."],
  },
  {
    id: "db_hip_thrust",
    name: "Dumbbell Hip Thrust",
    equipment: ["dumbbell", "bench"],
    pattern: "hinge",
    muscles: ["Glutes", "Hamstrings"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["hip"],
    harder: "hip_thrust",
    substitutes: ["hip_thrust", "glute_bridge"],
    cues: ["Upper back on the bench, a dumbbell held on your hips.", "Drive up until your body is flat from shoulders to knees, and squeeze."],
  },
  {
    id: "cable_pull_through",
    name: "Cable Pull-Through",
    equipment: ["cable"],
    pattern: "hinge",
    muscles: ["Glutes", "Hamstrings"],
    compound: true,
    level: 1,
    unit: "weight_reps",
    loads: ["hip", "spine"],
    substitutes: ["kb_swing", "db_rdl"],
    cues: ["Face away from a low cable, rope between your legs.", "Hinge back with a flat back, then drive your hips forward to stand tall."],
  },
  {
    id: "hip_abduction_machine",
    name: "Hip Abduction Machine",
    equipment: ["machine"],
    pattern: "isolation",
    muscles: ["Glutes"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["hip"],
    lowImpact: true,
    substitutes: ["band_lateral_walk", "standing_hip_abduction"],
    cues: ["Push the pads apart with your knees, pause, then return slowly.", "These muscles steady the pelvis when you walk and stand on one leg."],
  },
  {
    id: "machine_calf_raise",
    name: "Machine Calf Raise",
    equipment: ["machine"],
    pattern: "isolation",
    muscles: ["Calves"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["ankle"],
    lowImpact: true,
    substitutes: ["db_calf_raise", "calf_raise"],
    cues: ["Let the heels drop for a full stretch, then rise as high as you can.", "Pause at the top — bouncing does the work for you."],
  },
  {
    id: "cable_pallof_press",
    name: "Cable Pallof Press",
    equipment: ["cable"],
    pattern: "core",
    muscles: ["Core", "Obliques"],
    compound: false,
    level: 1,
    unit: "weight_reps",
    loads: ["spine"],
    lowImpact: true,
    substitutes: ["band_pallof_press", "plank"],
    cues: ["Stand side-on to the cable, handle at your chest.", "Press it straight out and hold, resisting the pull to twist."],
  },
];
