import type { Metadata } from "next";
import Link from "next/link";
import { Bullets, EmailLink, LegalPage, OPERATOR, Section } from "@/components/LegalPage";
import { PLANS } from "@/lib/billing/plans";

export const metadata: Metadata = {
  title: "Terms of Service — Your Personal Trainer",
};

export default function Terms() {
  return (
    <LegalPage
      title="Terms of Service"
      summary={
        <>
          <p>You need to be 16 or older. If you&apos;re under 18, get a parent or guardian&apos;s permission first.</p>
          <p>
            Everyone gets 10 days free with no card. After that it&apos;s {PLANS.month.price} a month or{" "}
            {PLANS.year.price} a year, and you can cancel any time in Settings.
          </p>
          <p>
            The app gives training guidance, not medical advice. Check with a doctor before starting if you have a
            health condition, and stop if something hurts.
          </p>
          <p>Your rights under the Australian Consumer Law always apply, whatever these terms say.</p>
        </>
      }
    >
      <Section id="about" number={1} title="Who we are">
        <p>
          Your Personal Trainer (&ldquo;the app&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;) is operated by{" "}
          {OPERATOR.name}, a sole trader based in {OPERATOR.location}. You can contact us at <EmailLink />.
        </p>
        <p>
          These terms are an agreement between you and us about your use of the app. By creating an account, you
          agree to them. If you don&apos;t agree, please don&apos;t use the app. Our{" "}
          <Link href="/privacy" className="text-accent underline underline-offset-4">
            Privacy Policy
          </Link>{" "}
          explains how we handle your personal information and forms part of these terms.
        </p>
      </Section>

      <Section id="eligibility" number={2} title="Who can use the app">
        <p>You must be at least 16 years old to create an account.</p>
        <p>
          If you are 16 or 17, you must have permission from a parent or guardian to use the app and to take out a
          subscription, and we recommend they read these terms with you. Nothing in these terms limits any rights
          you have under the law because of your age.
        </p>
      </Section>

      <Section id="service" number={3} title="What the app does">
        <p>
          The app builds a training plan from the answers you give, adjusts your targets based on the workouts you
          log, provides an AI coach you can ask questions, and summarises published exercise research.
        </p>
        <p>
          The app is not a doctor, physiotherapist or other health professional, and it does not supervise you in
          person. It does not diagnose or treat any illness, injury or condition.
        </p>
      </Section>

      <Section id="safety" number={4} title="Your health and safety">
        <p>Exercise carries a risk of injury. Please read this section carefully.</p>
        <Bullets
          items={[
            "Speak to a doctor or other qualified health professional before starting if you have a medical condition, an injury, are pregnant or have recently given birth, take medication that affects exercise, or haven't exercised in a long time.",
            "Stop exercising and seek medical help straight away if you experience chest pain, dizziness, faintness, unusual shortness of breath, or sharp or worsening pain.",
            "Targets, weights and exercises in the app are suggestions. You are best placed to judge what's safe for your body on the day — lift within your ability, use proper technique, and use appropriate equipment and supervision.",
            "Information about injuries or limitations you give us is used to steer the exercises we suggest. It does not mean the app has assessed that injury, and it isn't a substitute for professional advice about it.",
          ]}
        />
      </Section>

      <Section id="coach" number={5} title="The AI coach">
        <p>
          The coach&apos;s replies are generated by artificial intelligence, using a model provided by Anthropic. It
          is given your plan, profile and recent workouts so its answers are relevant to you, and a library of
          published research so its advice is grounded.
        </p>
        <p>
          AI can still be wrong, out of date or incomplete. Treat its replies as general guidance, not professional
          advice, and don&apos;t rely on it for decisions about your health. Please don&apos;t enter other people&apos;s
          personal information into it.
        </p>
        <p>
          To keep the service fair and running, the coach has usage limits (currently 10 messages a minute and 100 a
          day). We may change these limits, but not in a way that stops you using the coach for ordinary personal
          training questions.
        </p>
      </Section>

      <Section id="trial" number={6} title="Free trial">
        <p>
          New accounts get 10 days of full access, starting when the account is created. You don&apos;t need to give
          payment details to start the trial, and you will not be charged when it ends. We will email you before your
          trial ends.
        </p>
        <p>
          When the trial ends, you&apos;ll need a subscription to keep using the app. Your plan, workout history and
          progress stay saved in your account. The free trial is limited to one per person.
        </p>
      </Section>

      <Section id="subscriptions" number={7} title="Subscriptions and payment">
        <Bullets
          items={[
            <>
              A subscription costs {PLANS.month.price} a month or {PLANS.year.price} a year, in Australian dollars.
              We are not registered for GST, so no GST is added: the price shown is the total you pay.
            </>,
            "Payments are processed by Stripe. We never receive or store your full card details.",
            "Your subscription renews automatically at the end of each monthly or yearly period, and you'll be charged the same amount unless we've told you about a price change, until you cancel. We will email you before a yearly subscription renews.",
            "If we change the price, we'll email you at least 30 days before it applies to you, so you can cancel beforehand if you don't want to continue. A price change never applies to a period you've already paid for.",
            "If a payment fails, Stripe will try again over a short period. If payment still can't be collected, your access may be paused until it's resolved.",
          ]}
        />
      </Section>

      <Section id="cancelling" number={8} title="Cancelling and refunds">
        <p>
          You can cancel at any time in the app, under Settings, then Manage billing. Cancelling stops future
          payments. You keep access until the end of the period you&apos;ve already paid for, and you won&apos;t be
          charged again.
        </p>
        <p>
          We don&apos;t give refunds for part of a period if you simply change your mind. This does not affect your
          rights under the Australian Consumer Law, which are set out in the next section and always apply.
        </p>
      </Section>

      <Section id="consumer-law" number={9} title="Your rights under the Australian Consumer Law">
        <p>
          Our services come with guarantees that cannot be excluded under the Australian Consumer Law. These include
          that the services will be provided with due care and skill, and will be reasonably fit for any purpose you
          have told us about.
        </p>
        <p>
          For a major failure with the service, you are entitled to cancel your subscription and receive a refund for
          the unused portion, or to receive compensation for its reduced value. If a failure is not major, we will fix
          it within a reasonable time; if we don&apos;t, you may cancel and receive a refund for the unused portion.
          You may also be entitled to compensation for other reasonably foreseeable loss or damage caused by a
          failure.
        </p>
        <p>Nothing in these terms excludes, restricts or modifies any of these rights.</p>
      </Section>

      <Section id="acceptable-use" number={10} title="Using the app fairly">
        <p>When you use the app, you agree not to:</p>
        <Bullets
          items={[
            "access or try to access anyone else's account or data;",
            "interfere with, overload or try to get around the app's security, usage limits or payment checks;",
            "copy, scrape, resell or commercially exploit the app or its content;",
            "use the app, including the coach, for anything unlawful, harmful or abusive; or",
            "share your account with other people.",
          ]}
        />
      </Section>

      <Section id="your-data" number={11} title="Your information">
        <p>
          The workouts, answers and other information you put into the app remain yours. You allow us to store and
          use them only to provide the app to you, as described in our Privacy Policy. You can ask us to delete your
          account and information at any time by emailing <EmailLink />.
        </p>
      </Section>

      <Section id="ip" number={12} title="Our content">
        <p>
          The app, its design, software and written content belong to us or the people we license them from. We give
          you a personal, non-transferable right to use the app for your own training while you have an account.
          Research papers referred to in the app belong to their authors and publishers.
        </p>
      </Section>

      <Section id="changes-to-service" number={13} title="Availability and changes to the app">
        <p>
          We work to keep the app available and reliable, but it may occasionally be unavailable for maintenance or
          because of problems outside our control. We improve the app over time, which can mean changing or replacing
          features.
        </p>
        <p>
          If we stop offering the app altogether, or remove a significant part of what you&apos;ve paid for, we will
          give you reasonable notice by email and refund the unused portion of any period you have paid for.
        </p>
      </Section>

      <Section id="ending" number={14} title="Closing an account">
        <p>
          You can stop using the app and cancel your subscription at any time, and ask us to delete your account.
        </p>
        <p>
          We may suspend or close an account if its owner seriously or repeatedly breaches these terms, uses the app
          fraudulently, or if we are required to by law. Where it&apos;s reasonable to do so, we&apos;ll tell you
          first and give you a chance to fix the problem. If we close your account for a reason that isn&apos;t your
          breach of these terms, we&apos;ll refund the unused portion of any period you&apos;ve paid for.
        </p>
      </Section>

      <Section id="liability" number={15} title="Our responsibility to you">
        <p>
          Nothing in these terms excludes or limits any liability that cannot be excluded or limited by law,
          including under the Australian Consumer Law.
        </p>
        <p>
          Subject to that, we are not responsible for loss that was not reasonably foreseeable, or for injury or loss
          to the extent it is caused by you not following the safety guidance in section 4, such as continuing to
          exercise through the warning signs listed there or ignoring advice from your own health professional.
        </p>
      </Section>

      <Section id="third-parties" number={16} title="Other services we rely on">
        <p>
          Some parts of the app are provided by other companies, such as Stripe for payments and Google if you choose
          to sign in with Google. Your use of those services is also subject to their own terms.
        </p>
      </Section>

      <Section id="changes-to-terms" number={17} title="Changes to these terms">
        <p>
          We may update these terms, for example to reflect changes to the app or the law. If a change is significant,
          we&apos;ll email you at least 30 days before it takes effect. If you don&apos;t agree with it, you can cancel
          before then and you won&apos;t be charged again. Changes never apply to a period you&apos;ve already paid
          for.
        </p>
      </Section>

      <Section id="complaints" number={18} title="Problems and complaints">
        <p>
          If something goes wrong, please email us at <EmailLink /> first. We aim to reply within 10 business days
          and to resolve things fairly.
        </p>
        <p>
          If you&apos;re not satisfied, you can contact{" "}
          <a href="https://cbos.tas.gov.au" className="text-accent underline underline-offset-4">
            Consumer, Building and Occupational Services Tasmania
          </a>{" "}
          or the consumer protection agency in your own state or territory.
        </p>
      </Section>

      <Section id="law" number={19} title="Governing law">
        <p>
          These terms are governed by the law of Tasmania, Australia. This doesn&apos;t take away any protection you
          have under the consumer laws of the place you live.
        </p>
        <p>
          If any part of these terms is found to be unenforceable, the rest continues to apply. If we don&apos;t
          enforce a term straight away, we haven&apos;t given up our right to enforce it later.
        </p>
      </Section>
    </LegalPage>
  );
}
